coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
    changes:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  require_changes: true
  behavior: default
  show_coverage_change: yes
  show_project_coverage: yes
  show_diff_coverage: yes
