#pragma once

#include <array>
#include <span>
#include <string_view>

namespace faker::animal
{
struct AnimalDefinition
{
    std::span<const std::string_view> bears;
    std::span<const std::string_view> birds;
    std::span<const std::string_view> cats;
    std::span<const std::string_view> cetaceans;
    std::span<const std::string_view> cows;
    std::span<const std::string_view> crocodiles;
    std::span<const std::string_view> dogs;
    std::span<const std::string_view> fishes;
    std::span<const std::string_view> horses;
    std::span<const std::string_view> insects;
    std::span<const std::string_view> lions;
    std::span<const std::string_view> rabbits;
    std::span<const std::string_view> rodents;
    std::span<const std::string_view> snakes;
    std::span<const std::string_view> types;
};

const auto enUSBears = std::to_array<std::string_view>({
    "American black bear",
    "Asian black bear",
    "Brown bear",
    "Giant panda",
    "Polar bear",
    "Sloth bear",
    "Spectacled bear",
    "Sun bear",
});

const auto enUSBirds = std::to_array<std::string_view>({
    "Abert's Towhee",
    "Acadian Flycatcher",
    "Acorn Woodpecker",
    "Alder Flycatcher",
    "Aleutian Tern",
    "Allen's Hummingbird",
    "Altamira Oriole",
    "American Avocet",
    "American Bittern",
    "American Black Duck",
    "American Coot",
    "American Crow",
    "American Dipper",
    "American Golden-Plover",
    "American Goldfinch",
    "American Kestrel",
    "American Oystercatcher",
    "American Pipit",
    "American Redstart",
    "American Robin",
    "American Tree Sparrow",
    "American White Pelican",
    "American Wigeon",
    "American Woodcock",
    "Ancient Murrelet",
    "Anhinga",
    "Anna's Hummingbird",
    "Antillean Nighthawk",
    "Antillean Palm Swift",
    "Aplomado Falcon",
    "Arctic Loon",
    "Arctic Tern",
    "Arctic Warbler",
    "Ash-throated Flycatcher",
    "Ashy Storm-Petrel",
    "Asian Brown Flycatcher",
    "Atlantic Puffin",
    "Audubon's Oriole",
    "Audubon's Shearwater",
    "Aztec Thrush",
    "Azure Gallinule",
    "Bachman's Sparrow",
    "Bachman's Warbler",
    "Bahama Mockingbird",
    "Bahama Swallow",
    "Bahama Woodstar",
    "Baikal Teal",
    "Baird's Sandpiper",
    "Baird's Sparrow",
    "Bald Eagle",
    "Baltimore Oriole",
    "Bananaquit",
    "Band-rumped Storm-Petrel",
    "Band-tailed Gull",
    "Band-tailed Pigeon",
    "Bank Swallow",
    "Bar-tailed Godwit",
    "Barn Owl",
    "Barn Swallow",
    "Barnacle Goose",
    "Barred Owl",
    "Barrow's Goldeneye",
    "Bay-breasted Warbler",
    "Bean Goose",
    "Bell's Vireo",
    "Belted Kingfisher",
    "Bendire's Thrasher",
    "Berylline Hummingbird",
    "Bewick's Wren",
    "Bicknell's Thrush",
    "Black Catbird",
    "Black Guillemot",
    "Black Noddy",
    "Black Oystercatcher",
    "Black Phoebe",
    "Black Rail",
    "Black Rosy-Finch",
    "Black Scoter",
    "Black Skimmer",
    "Black Storm-Petrel",
    "Black Swift",
    "Black Tern",
    "Black Turnstone",
    "Black Vulture",
    "Black-and-white Warbler",
    "Black-backed Wagtail",
    "Black-backed Woodpecker",
    "Black-bellied Plover",
    "Black-bellied Whistling-Duck",
    "Black-billed Cuckoo",
    "Black-billed Magpie",
    "Black-browed Albatross",
    "Black-capped Chickadee",
    "Black-capped Gnatcatcher",
    "Black-capped Petrel",
    "Black-capped Vireo",
    "Black-chinned Hummingbird",
    "Black-chinned Sparrow",
    "Black-crowned Night-Heron",
    "Black-faced Grassquit",
    "Black-footed Albatross",
    "Black-headed Grosbeak",
    "Black-headed Gull",
    "Black-legged Kittiwake",
    "Black-necked Stilt",
    "Black-tailed Gnatcatcher",
    "Black-tailed Godwit",
    "Black-tailed Gull",
    "Black-throated Blue Warbler",
    "Black-throated Gray Warbler",
    "Black-throated Green Warbler",
    "Black-throated Sparrow",
    "Black-vented Oriole",
    "Black-vented Shearwater",
    "Black-whiskered Vireo",
    "Black-winged Stilt",
    "Blackburnian Warbler",
    "Blackpoll Warbler",
    "Blue Bunting",
    "Blue Grosbeak",
    "Blue Grouse",
    "Blue Jay",
    "Blue Mockingbird",
    "Blue-footed Booby",
    "Blue-gray Gnatcatcher",
    "Blue-headed Vireo",
    "Blue-throated Hummingbird",
    "Blue-winged Teal",
    "Blue-winged Warbler",
    "Bluethroat",
    "Boat-tailed Grackle",
    "Bobolink",
    "Bohemian Waxwing",
    "Bonaparte's Gull",
    "Boreal Chickadee",
    "Boreal Owl",
    "Botteri's Sparrow",
    "Brambling",
    "Brandt's Cormorant",
    "Brant",
    "Brewer's Blackbird",
    "Brewer's Sparrow",
    "Bridled Tern",
    "Bridled Titmouse",
    "Bristle-thighed Curlew",
    "Broad-billed Hummingbird",
    "Broad-billed Sandpiper",
    "Broad-tailed Hummingbird",
    "Broad-winged Hawk",
    "Bronzed Cowbird",
    "Brown Booby",
    "Brown Creeper",
    "Brown Jay",
    "Brown Noddy",
    "Brown Pelican",
    "Brown Shrike",
    "Brown Thrasher",
    "Brown-capped Rosy-Finch",
    "Brown-chested Martin",
    "Brown-crested Flycatcher",
    "Brown-headed Cowbird",
    "Brown-headed Nuthatch",
    "Budgerigar",
    "Buff-bellied Hummingbird",
    "Buff-breasted Flycatcher",
    "Buff-breasted Sandpiper",
    "Buff-collared Nightjar",
    "Bufflehead",
    "Buller's Shearwater",
    "Bullock's Oriole",
    "Bumblebee Hummingbird",
    "Burrowing Owl",
    "Bushtit",
    "Cactus Wren",
    "California Condor",
    "California Gnatcatcher",
    "California Gull",
    "California Quail",
    "California Thrasher",
    "California Towhee",
    "Calliope Hummingbird",
    "Canada Goose",
    "Canada Warbler",
    "Canvasback",
    "Canyon Towhee",
    "Canyon Wren",
    "Cape May Warbler",
    "Caribbean Elaenia",
    "Carolina Chickadee",
    "Carolina Parakeet",
    "Carolina Wren",
    "Caspian Tern",
    "Cassin's Auklet",
    "Cassin's Finch",
    "Cassin's Kingbird",
    "Cassin's Sparrow",
    "Cassin's Vireo",
    "Cattle Egret",
    "Cave Swallow",
    "Cedar Waxwing",
    "Cerulean Warbler",
    "Chestnut-backed Chickadee",
    "Chestnut-collared Longspur",
    "Chestnut-sided Warbler",
    "Chihuahuan Raven",
    "Chimney Swift",
    "Chinese Egret",
    "Chipping Sparrow",
    "Chuck-will's-widow",
    "Chukar",
    "Cinnamon Hummingbird",
    "Cinnamon Teal",
    "Citrine Wagtail",
    "Clapper Rail",
    "Clark's Grebe",
    "Clark's Nutcracker",
    "Clay-colored Robin",
    "Clay-colored Sparrow",
    "Cliff Swallow",
    "Colima Warbler",
    "Collared Forest-Falcon",
    "Collared Plover",
    "Common Black-Hawk",
    "Common Chaffinch",
    "Common Crane",
    "Common Cuckoo",
    "Common Eider",
    "Common Goldeneye",
    "Common Grackle",
    "Common Greenshank",
    "Common Ground-Dove",
    "Common House-Martin",
    "Common Loon",
    "Common Merganser",
    "Common Moorhen",
    "Common Murre",
    "Common Nighthawk",
    "Common Pauraque",
    "Common Pochard",
    "Common Poorwill",
    "Common Raven",
    "Common Redpoll",
    "Common Ringed Plover",
    "Common Rosefinch",
    "Common Sandpiper",
    "Common Snipe",
    "Common Swift",
    "Common Tern",
    "Common Yellowthroat",
    "Connecticut Warbler",
    "Cook's Petrel",
    "Cooper's Hawk",
    "Cordilleran Flycatcher",
    "Corn Crake",
    "Cory's Shearwater",
    "Costa's Hummingbird",
    "Couch's Kingbird",
    "Crane Hawk",
    "Craveri's Murrelet",
    "Crescent-chested Warbler",
    "Crested Auklet",
    "Crested Caracara",
    "Crested Myna",
    "Crimson-collared Grosbeak",
    "Crissal Thrasher",
    "Cuban Martin",
    "Curlew Sandpiper",
    "Curve-billed Thrasher",
    "Dark-eyed Junco",
    "Dickcissel",
    "Double-crested Cormorant",
    "Double-striped Thick-knee",
    "Dovekie",
    "Downy Woodpecker",
    "Dunlin",
    "Dusky Flycatcher",
    "Dusky Thrush",
    "Dusky Warbler",
    "Dusky-capped Flycatcher",
    "Eared Grebe",
    "Eared Trogon",
    "Eastern Bluebird",
    "Eastern Kingbird",
    "Eastern Meadowlark",
    "Eastern Phoebe",
    "Eastern Screech-Owl",
    "Eastern Towhee",
    "Eastern Wood-Pewee",
    "Elegant Tern",
    "Elegant Trogon",
    "Elf Owl",
    "Emperor Goose",
    "Eskimo Curlew",
    "Eurasian Blackbird",
    "Eurasian Bullfinch",
    "Eurasian Collared-Dove",
    "Eurasian Coot",
    "Eurasian Curlew",
    "Eurasian Dotterel",
    "Eurasian Hobby",
    "Eurasian Jackdaw",
    "Eurasian Kestrel",
    "Eurasian Oystercatcher",
    "Eurasian Siskin",
    "Eurasian Tree Sparrow",
    "Eurasian Wigeon",
    "Eurasian Woodcock",
    "Eurasian Wryneck",
    "European Golden-Plover",
    "European Starling",
    "European Storm-Petrel",
    "European Turtle-Dove",
    "Evening Grosbeak",
    "Eyebrowed Thrush",
    "Falcated Duck",
    "Fan-tailed Warbler",
    "Far Eastern Curlew",
    "Ferruginous Hawk",
    "Ferruginous Pygmy-Owl",
    "Field Sparrow",
    "Fieldfare",
    "Fish Crow",
    "Five-striped Sparrow",
    "Flame-colored Tanager",
    "Flammulated Owl",
    "Flesh-footed Shearwater",
    "Florida Scrub-Jay",
    "Fork-tailed Flycatcher",
    "Fork-tailed Storm-Petrel",
    "Fork-tailed Swift",
    "Forster's Tern",
    "Fox Sparrow",
    "Franklin's Gull",
    "Fulvous Whistling-Duck",
    "Gadwall",
    "Gambel's Quail",
    "Garganey",
    "Gila Woodpecker",
    "Gilded Flicker",
    "Glaucous Gull",
    "Glaucous-winged Gull",
    "Glossy Ibis",
    "Golden Eagle",
    "Golden-cheeked Warbler",
    "Golden-crowned Kinglet",
    "Golden-crowned Sparrow",
    "Golden-crowned Warbler",
    "Golden-fronted Woodpecker",
    "Golden-winged Warbler",
    "Grace's Warbler",
    "Grasshopper Sparrow",
    "Gray Bunting",
    "Gray Catbird",
    "Gray Flycatcher",
    "Gray Hawk",
    "Gray Jay",
    "Gray Kingbird",
    "Gray Partridge",
    "Gray Silky-flycatcher",
    "Gray Vireo",
    "Gray Wagtail",
    "Gray-breasted Martin",
    "Gray-cheeked Thrush",
    "Gray-crowned Rosy-Finch",
    "Gray-crowned Yellowthroat",
    "Gray-headed Chickadee",
    "Gray-spotted Flycatcher",
    "Gray-tailed Tattler",
    "Great Auk",
    "Great Black-backed Gull",
    "Great Blue Heron",
    "Great Cormorant",
    "Great Crested Flycatcher",
    "Great Egret",
    "Great Frigatebird",
    "Great Gray Owl",
    "Great Horned Owl",
    "Great Kiskadee",
    "Great Knot",
    "Great Skua",
    "Great Spotted Woodpecker",
    "Great-tailed Grackle",
    "Greater Flamingo",
    "Greater Pewee",
    "Greater Prairie-chicken",
    "Greater Roadrunner",
    "Greater Scaup",
    "Greater Shearwater",
    "Greater White-fronted Goose",
    "Greater Yellowlegs",
    "Green Heron",
    "Green Jay",
    "Green Kingfisher",
    "Green Sandpiper",
    "Green Violet-ear",
    "Green-breasted Mango",
    "Green-tailed Towhee",
    "Green-winged Teal",
    "Greenish Elaenia",
    "Groove-billed Ani",
    "Gull-billed Tern",
    "Gyrfalcon",
    "Hairy Woodpecker",
    "Hammond's Flycatcher",
    "Harlequin Duck",
    "Harris's Hawk",
    "Harris's Sparrow",
    "Hawfinch",
    "Heermann's Gull",
    "Henslow's Sparrow",
    "Hepatic Tanager",
    "Herald Petrel",
    "Hermit Thrush",
    "Hermit Warbler",
    "Herring Gull",
    "Himalayan Snowcock",
    "Hoary Redpoll",
    "Hooded Merganser",
    "Hooded Oriole",
    "Hooded Warbler",
    "Hook-billed Kite",
    "Hoopoe",
    "Horned Grebe",
    "Horned Lark",
    "Horned Puffin",
    "House Finch",
    "House Sparrow",
    "House Wren",
    "Hudsonian Godwit",
    "Hutton's Vireo",
    "Iceland Gull",
    "Inca Dove",
    "Indigo Bunting",
    "Island Scrub-Jay",
    "Ivory Gull",
    "Ivory-billed Woodpecker",
    "Jabiru",
    "Jack Snipe",
    "Jungle Nightjar",
    "Juniper Titmouse",
    "Kentucky Warbler",
    "Key West Quail-Dove",
    "Killdeer",
    "King Eider",
    "King Rail",
    "Kirtland's Warbler",
    "Kittlitz's Murrelet",
    "La Sagra's Flycatcher",
    "Labrador Duck",
    "Ladder-backed Woodpecker",
    "Lanceolated Warbler",
    "Lapland Longspur",
    "Large-billed Tern",
    "Lark Bunting",
    "Lark Sparrow",
    "Laughing Gull",
    "Lawrence's Goldfinch",
    "Laysan Albatross",
    "Lazuli Bunting",
    "Le Conte's Sparrow",
    "Le Conte's Thrasher",
    "Leach's Storm-Petrel",
    "Least Auklet",
    "Least Bittern",
    "Least Flycatcher",
    "Least Grebe",
    "Least Sandpiper",
    "Least Storm-Petrel",
    "Least Tern",
    "Lesser Black-backed Gull",
    "Lesser Frigatebird",
    "Lesser Goldfinch",
    "Lesser Nighthawk",
    "Lesser Prairie-chicken",
    "Lesser Scaup",
    "Lesser White-fronted Goose",
    "Lesser Yellowlegs",
    "Lewis's Woodpecker",
    "Limpkin",
    "Lincoln's Sparrow",
    "Little Blue Heron",
    "Little Bunting",
    "Little Curlew",
    "Little Egret",
    "Little Gull",
    "Little Ringed Plover",
    "Little Shearwater",
    "Little Stint",
    "Loggerhead Kingbird",
    "Loggerhead Shrike",
    "Long-billed Curlew",
    "Long-billed Dowitcher",
    "Long-billed Murrelet",
    "Long-billed Thrasher",
    "Long-eared Owl",
    "Long-tailed Jaeger",
    "Long-toed Stint",
    "Louisiana Waterthrush",
    "Lucifer Hummingbird",
    "Lucy's Warbler",
    "MacGillivray's Warbler",
    "Magnificent Frigatebird",
    "Magnificent Hummingbird",
    "Magnolia Warbler",
    "Mallard",
    "Mangrove Cuckoo",
    "Manx Shearwater",
    "Marbled Godwit",
    "Marbled Murrelet",
    "Marsh Sandpiper",
    "Marsh Wren",
    "Masked Booby",
    "Masked Duck",
    "Masked Tityra",
    "McCown's Longspur",
    "McKay's Bunting",
    "Merlin",
    "Mew Gull",
    "Mexican Chickadee",
    "Mexican Jay",
    "Middendorff's Grasshopper-Warbler",
    "Mississippi Kite",
    "Mongolian Plover",
    "Monk Parakeet",
    "Montezuma Quail",
    "Mottled Duck",
    "Mottled Owl",
    "Mottled Petrel",
    "Mountain Bluebird",
    "Mountain Chickadee",
    "Mountain Plover",
    "Mountain Quail",
    "Mourning Dove",
    "Mourning Warbler",
    "Mugimaki Flycatcher",
    "Murphy's Petrel",
    "Muscovy Duck",
    "Mute Swan",
    "Narcissus Flycatcher",
    "Nashville Warbler",
    "Nelson's Sharp-tailed Sparrow",
    "Neotropic Cormorant",
    "Northern Beardless-Tyrannulet",
    "Northern Bobwhite",
    "Northern Cardinal",
    "Northern Flicker",
    "Northern Fulmar",
    "Northern Gannet",
    "Northern Goshawk",
    "Northern Harrier",
    "Northern Hawk Owl",
    "Northern Jacana",
    "Northern Lapwing",
    "Northern Mockingbird",
    "Northern Parula",
    "Northern Pintail",
    "Northern Pygmy-Owl",
    "Northern Rough-winged Swallow",
    "Northern Saw-whet Owl",
    "Northern Shoveler",
    "Northern Shrike",
    "Northern Waterthrush",
    "Northern Wheatear",
    "Northwestern Crow",
    "Nuttall's Woodpecker",
    "Nutting's Flycatcher",
    "Oak Titmouse",
    "Oldsquaw",
    "Olive Sparrow",
    "Olive Warbler",
    "Olive-backed Pipit",
    "Olive-sided Flycatcher",
    "Orange-crowned Warbler",
    "Orchard Oriole",
    "Oriental Cuckoo",
    "Oriental Greenfinch",
    "Oriental Pratincole",
    "Oriental Scops-Owl",
    "Oriental Turtle-Dove",
    "Osprey",
    "Ovenbird",
    "Pacific Golden-Plover",
    "Pacific Loon",
    "Pacific-slope Flycatcher",
    "Paint-billed Crake",
    "Painted Bunting",
    "Painted Redstart",
    "Pallas's Bunting",
    "Palm Warbler",
    "Parakeet Auklet",
    "Parasitic Jaeger",
    "Passenger Pigeon",
    "Pechora Pipit",
    "Pectoral Sandpiper",
    "Pelagic Cormorant",
    "Peregrine Falcon",
    "Phainopepla",
    "Philadelphia Vireo",
    "Pied-billed Grebe",
    "Pigeon Guillemot",
    "Pileated Woodpecker",
    "Pin-tailed Snipe",
    "Pine Bunting",
    "Pine Grosbeak",
    "Pine Siskin",
    "Pine Warbler",
    "Pink-footed Goose",
    "Pink-footed Shearwater",
    "Pinyon Jay",
    "Piping Plover",
    "Plain Chachalaca",
    "Plain-capped Starthroat",
    "Plumbeous Vireo",
    "Pomarine Jaeger",
    "Prairie Falcon",
    "Prairie Warbler",
    "Prothonotary Warbler",
    "Purple Finch",
    "Purple Gallinule",
    "Purple Martin",
    "Purple Sandpiper",
    "Pygmy Nuthatch",
    "Pyrrhuloxia",
    "Razorbill",
    "Red Crossbill",
    "Red Knot",
    "Red Phalarope",
    "Red-bellied Woodpecker",
    "Red-billed Pigeon",
    "Red-billed Tropicbird",
    "Red-breasted Flycatcher",
    "Red-breasted Merganser",
    "Red-breasted Nuthatch",
    "Red-breasted Sapsucker",
    "Red-cockaded Woodpecker",
    "Red-crowned Parrot",
    "Red-eyed Vireo",
    "Red-faced Cormorant",
    "Red-faced Warbler",
    "Red-flanked Bluetail",
    "Red-footed Booby",
    "Red-headed Woodpecker",
    "Red-legged Kittiwake",
    "Red-naped Sapsucker",
    "Red-necked Grebe",
    "Red-necked Phalarope",
    "Red-necked Stint",
    "Red-shouldered Hawk",
    "Red-tailed Hawk",
    "Red-tailed Tropicbird",
    "Red-throated Loon",
    "Red-throated Pipit",
    "Red-whiskered Bulbul",
    "Red-winged Blackbird",
    "Reddish Egret",
    "Redhead",
    "Redwing",
    "Reed Bunting",
    "Rhinoceros Auklet",
    "Ring-billed Gull",
    "Ring-necked Duck",
    "Ring-necked Pheasant",
    "Ringed Kingfisher",
    "Roadside Hawk",
    "Rock Dove",
    "Rock Ptarmigan",
    "Rock Sandpiper",
    "Rock Wren",
    "Rose-breasted Grosbeak",
    "Rose-throated Becard",
    "Roseate Spoonbill",
    "Roseate Tern",
    "Ross's Goose",
    "Ross's Gull",
    "Rough-legged Hawk",
    "Royal Tern",
    "Ruby-crowned Kinglet",
    "Ruby-throated Hummingbird",
    "Ruddy Duck",
    "Ruddy Ground-Dove",
    "Ruddy Quail-Dove",
    "Ruddy Turnstone",
    "Ruff",
    "Ruffed Grouse",
    "Rufous Hummingbird",
    "Rufous-backed Robin",
    "Rufous-capped Warbler",
    "Rufous-crowned Sparrow",
    "Rufous-winged Sparrow",
    "Rustic Bunting",
    "Rusty Blackbird",
    "Sabine's Gull",
    "Sage Grouse",
    "Sage Sparrow",
    "Sage Thrasher",
    "Saltmarsh Sharp-tailed Sparrow",
    "Sanderling",
    "Sandhill Crane",
    "Sandwich Tern",
    "Savannah Sparrow",
    "Say's Phoebe",
    "Scaled Quail",
    "Scaly-naped Pigeon",
    "Scarlet Ibis",
    "Scarlet Tanager",
    "Scissor-tailed Flycatcher",
    "Scott's Oriole",
    "Seaside Sparrow",
    "Sedge Wren",
    "Semipalmated Plover",
    "Semipalmated Sandpiper",
    "Sharp-shinned Hawk",
    "Sharp-tailed Grouse",
    "Sharp-tailed Sandpiper",
    "Shiny Cowbird",
    "Short-billed Dowitcher",
    "Short-eared Owl",
    "Short-tailed Albatross",
    "Short-tailed Hawk",
    "Short-tailed Shearwater",
    "Shy Albatross",
    "Siberian Accentor",
    "Siberian Blue Robin",
    "Siberian Flycatcher",
    "Siberian Rubythroat",
    "Sky Lark",
    "Slate-throated Redstart",
    "Slaty-backed Gull",
    "Slender-billed Curlew",
    "Smew",
    "Smith's Longspur",
    "Smooth-billed Ani",
    "Snail Kite",
    "Snow Bunting",
    "Snow Goose",
    "Snowy Egret",
    "Snowy Owl",
    "Snowy Plover",
    "Solitary Sandpiper",
    "Song Sparrow",
    "Sooty Shearwater",
    "Sooty Tern",
    "Sora",
    "South Polar Skua",
    "Southern Martin",
    "Spectacled Eider",
    "Spoonbill Sandpiper",
    "Spot-billed Duck",
    "Spot-breasted Oriole",
    "Spotted Dove",
    "Spotted Owl",
    "Spotted Rail",
    "Spotted Redshank",
    "Spotted Sandpiper",
    "Spotted Towhee",
    "Sprague's Pipit",
    "Spruce Grouse",
    "Stejneger's Petrel",
    "Steller's Eider",
    "Steller's Jay",
    "Steller's Sea-Eagle",
    "Stilt Sandpiper",
    "Stonechat",
    "Streak-backed Oriole",
    "Streaked Shearwater",
    "Strickland's Woodpecker",
    "Stripe-headed Tanager",
    "Sulphur-bellied Flycatcher",
    "Summer Tanager",
    "Surf Scoter",
    "Surfbird",
    "Swainson's Hawk",
    "Swainson's Thrush",
    "Swainson's Warbler",
    "Swallow-tailed Kite",
    "Swamp Sparrow",
    "Tamaulipas Crow",
    "Tawny-shouldered Blackbird",
    "Temminck's Stint",
    "Tennessee Warbler",
    "Terek Sandpiper",
    "Thayer's Gull",
    "Thick-billed Kingbird",
    "Thick-billed Murre",
    "Thick-billed Parrot",
    "Thick-billed Vireo",
    "Three-toed Woodpecker",
    "Townsend's Solitaire",
    "Townsend's Warbler",
    "Tree Pipit",
    "Tree Swallow",
    "Tricolored Blackbird",
    "Tricolored Heron",
    "Tropical Kingbird",
    "Tropical Parula",
    "Trumpeter Swan",
    "Tufted Duck",
    "Tufted Flycatcher",
    "Tufted Puffin",
    "Tufted Titmouse",
    "Tundra Swan",
    "Turkey Vulture",
    "Upland Sandpiper",
    "Varied Bunting",
    "Varied Thrush",
    "Variegated Flycatcher",
    "Vaux's Swift",
    "Veery",
    "Verdin",
    "Vermilion Flycatcher",
    "Vesper Sparrow",
    "Violet-crowned Hummingbird",
    "Violet-green Swallow",
    "Virginia Rail",
    "Virginia's Warbler",
    "Wandering Albatross",
    "Wandering Tattler",
    "Warbling Vireo",
    "Wedge-rumped Storm-Petrel",
    "Wedge-tailed Shearwater",
    "Western Bluebird",
    "Western Grebe",
    "Western Gull",
    "Western Kingbird",
    "Western Meadowlark",
    "Western Reef-Heron",
    "Western Sandpiper",
    "Western Screech-Owl",
    "Western Scrub-Jay",
    "Western Tanager",
    "Western Wood-Pewee",
    "Whimbrel",
    "Whip-poor-will",
    "Whiskered Auklet",
    "Whiskered Screech-Owl",
    "Whiskered Tern",
    "White Ibis",
    "White Wagtail",
    "White-breasted Nuthatch",
    "White-cheeked Pintail",
    "White-chinned Petrel",
    "White-collared Seedeater",
    "White-collared Swift",
    "White-crowned Pigeon",
    "White-crowned Sparrow",
    "White-eared Hummingbird",
    "White-eyed Vireo",
    "White-faced Ibis",
    "White-faced Storm-Petrel",
    "White-headed Woodpecker",
    "White-rumped Sandpiper",
    "White-tailed Eagle",
    "White-tailed Hawk",
    "White-tailed Kite",
    "White-tailed Ptarmigan",
    "White-tailed Tropicbird",
    "White-throated Needletail",
    "White-throated Robin",
    "White-throated Sparrow",
    "White-throated Swift",
    "White-tipped Dove",
    "White-winged Crossbill",
    "White-winged Dove",
    "White-winged Parakeet",
    "White-winged Scoter",
    "White-winged Tern",
    "Whooper Swan",
    "Whooping Crane",
    "Wild Turkey",
    "Willet",
    "Williamson's Sapsucker",
    "Willow Flycatcher",
    "Willow Ptarmigan",
    "Wilson's Phalarope",
    "Wilson's Plover",
    "Wilson's Storm-Petrel",
    "Wilson's Warbler",
    "Winter Wren",
    "Wood Duck",
    "Wood Sandpiper",
    "Wood Stork",
    "Wood Thrush",
    "Wood Warbler",
    "Worm-eating Warbler",
    "Worthen's Sparrow",
    "Wrentit",
    "Xantus's Hummingbird",
    "Xantus's Murrelet",
    "Yellow Bittern",
    "Yellow Grosbeak",
    "Yellow Rail",
    "Yellow Wagtail",
    "Yellow Warbler",
    "Yellow-bellied Flycatcher",
    "Yellow-bellied Sapsucker",
    "Yellow-billed Cuckoo",
    "Yellow-billed Loon",
    "Yellow-billed Magpie",
    "Yellow-breasted Bunting",
    "Yellow-breasted Chat",
    "Yellow-crowned Night-Heron",
    "Yellow-eyed Junco",
    "Yellow-faced Grassquit",
    "Yellow-footed Gull",
    "Yellow-green Vireo",
    "Yellow-headed Blackbird",
    "Yellow-legged Gull",
    "Yellow-nosed Albatross",
    "Yellow-rumped Warbler",
    "Yellow-throated Vireo",
    "Yellow-throated Warbler",
    "Yucatan Vireo",
    "Zenaida Dove",
    "Zone-tailed Hawk",
});

const auto enUSCats = std::to_array<std::string_view>({
    "Abyssinian",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Balinese",
    "Bengal",
    "Birman",
    "Bombay",
    "British Shorthair",
    "Burmese",
    "Chartreux",
    "Chausie",
    "Cornish Rex",
    "Devon Rex",
    "Donskoy",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Havana",
    "Highlander",
    "Himalayan",
    "Japanese Bobtail",
    "Korat",
    "Kurilian Bobtail",
    "LaPerm",
    "Maine Coon",
    "Manx",
    "Minskin",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest Cat",
    "Ocicat",
    "Ojos Azules",
    "Oriental",
    "Persian",
    "Peterbald",
    "Pixiebob",
    "Ragdoll",
    "Russian Blue",
    "Savannah",
    "Scottish Fold",
    "Selkirk Rex",
    "Serengeti",
    "Siamese",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Sokoke",
    "Somali",
    "Sphynx",
    "Thai",
    "Tonkinese",
    "Toyger",
    "Turkish Angora",
    "Turkish Van",
});

const auto enUSCetaceans = std::to_array<std::string_view>({
    "Amazon River Dolphin",
    "Arnoux's Beaked Whale",
    "Atlantic Humpbacked Dolphin",
    "Atlantic Spotted Dolphin",
    "Atlantic White-Sided Dolphin",
    "Australian Snubfin Dolphin",
    "Australian humpback Dolphin",
    "Blue Whale",
    "Bottlenose Dolphin",
    "Bryde’s whale",
    "Burrunan Dolphin",
    "Chilean Dolphin",
    "Chinese River Dolphin",
    "Chinese White Dolphin",
    "Clymene Dolphin",
    "Commerson’s Dolphin",
    "Costero",
    "Dusky Dolphin",
    "False Killer Whale",
    "Fin Whale",
    "Fraser’s Dolphin",
    "Ganges River Dolphin",
    "Guiana Dolphin",
    "Heaviside’s Dolphin",
    "Hector’s Dolphin",
    "Hourglass Dolphin",
    "Humpback whale",
    "Indo-Pacific Bottlenose Dolphin",
    "Indo-Pacific Hump-backed Dolphin",
    "Irrawaddy Dolphin",
    "Killer Whale (Orca)",
    "La Plata Dolphin",
    "Long-Beaked Common Dolphin",
    "Long-finned Pilot Whale",
    "Longman's Beaked Whale",
    "Melon-headed Whale",
    "Northern Rightwhale Dolphin",
    "Omura’s whale",
    "Pacific White-Sided Dolphin",
    "Pantropical Spotted Dolphin",
    "Peale’s Dolphin",
    "Pygmy Killer Whale",
    "Risso’s Dolphin",
    "Rough-Toothed Dolphin",
    "Sei Whale",
    "Short-Beaked Common Dolphin",
    "Short-finned Pilot Whale",
    "Southern Bottlenose Whale",
    "Southern Rightwhale Dolphin",
    "Sperm Whale",
    "Spinner Dolphin",
    "Striped Dolphin",
    "Tucuxi",
    "White-Beaked Dolphin",
});

const auto enUSCows = std::to_array<std::string_view>({
    "Aberdeen Angus",
    "Abergele",
    "Abigar",
    "Abondance",
    "Abyssinian Shorthorned Zebu",
    "Aceh",
    "Achham",
    "Adamawa",
    "Adaptaur",
    "Afar",
    "Africangus",
    "Afrikaner",
    "Agerolese",
    "Alambadi",
    "Alatau",
    "Albanian",
    "Albera",
    "Alderney",
    "Alentejana",
    "Aleutian wild cattle",
    "Aliad Dinka",
    "Alistana-Sanabresa",
    "Allmogekor",
    "Alur",
    "American",
    "American Angus",
    "American Beef Friesian",
    "American Brown Swiss",
    "American Milking Devon",
    "American White Park",
    "Amerifax",
    "Amrit Mahal",
    "Amsterdam Island cattle",
    "Anatolian Black",
    "Andalusian Black",
    "Andalusian Blond",
    "Andalusian Grey",
    "Angeln",
    "Angoni",
    "Ankina",
    "Ankole",
    "Ankole-Watusi",
    "Aracena",
    "Arado",
    "Argentine Criollo",
    "Argentine Friesian",
    "Armorican",
    "Arouquesa",
    "Arsi",
    "Asturian Mountain",
    "Asturian Valley",
    "Aubrac",
    "Aulie-Ata",
    "Aure et Saint-Girons",
    "Australian Braford",
    "Australian Brangus",
    "Australian Charbray",
    "Australian Friesian Sahiwal",
    "Australian Lowline",
    "Australian Milking Zebu",
    "Australian Shorthorn",
    "Austrian Simmental",
    "Austrian Yellow",
    "Avileña-Negra Ibérica",
    "Avétonou",
    "Aweil Dinka",
    "Ayrshire",
    "Azaouak",
    "Azebuado",
    "Azerbaijan Zebu",
    "Azores",
    "Bachaur cattle",
    "Baherie cattle",
    "Bakosi cattle",
    "Balancer",
    "Baoule",
    "Bargur cattle",
    "Barrosã",
    "Barzona",
    "Bazadaise",
    "Bedit",
    "Beef Freisian",
    "Beefalo",
    "Beefmaker",
    "Beefmaster",
    "Begayt",
    "Belgian Blue",
    "Belgian Red",
    "Belgian Red Pied",
    "Belgian White-and-Red",
    "Belmont Red",
    "Belted Galloway",
    "Bernese",
    "Berrenda cattle",
    "Betizu",
    "Bianca Modenese",
    "Blaarkop",
    "Black Angus",
    "Black Baldy",
    "Black Hereford",
    "Blanca Cacereña",
    "Blanco Orejinegro BON",
    "Blonde d'Aquitaine",
    "Blue Albion",
    "Blue Grey",
    "Bohuskulla",
    "Bonsmara",
    "Boran",
    "Boškarin",
    "Braford",
    "Brahman",
    "Brahmousin",
    "Brangus",
    "Braunvieh",
    "Brava",
    "Breed",
    "British Friesian",
    "British White",
    "Brown Carpathian",
    "Brown Caucasian",
    "Brown Swiss",
    "Bue Lingo",
    "Burlina",
    "Bushuyev",
    "Butana cattle",
    "Buša cattle",
    "Cachena",
    "Caldelana",
    "Camargue",
    "Campbell Island cattle",
    "Canadian Speckle Park",
    "Canadienne",
    "Canaria",
    "Canchim",
    "Caracu",
    "Carinthian Blondvieh",
    "Carora",
    "Cedit",
    "Charbray",
    "Charolais",
    "Chateaubriand",
    "Chiangus",
    "Chianina",
    "Chillingham cattle",
    "Chinese Black Pied",
    "Cholistani",
    "Coloursided White Back",
    "Commercial",
    "Corriente",
    "Corsican cattle",
    "Costeño con Cuernos",
    "Crioulo Lageano",
    "Cárdena Andaluza",
    "Dajal",
    "Dangi cattle",
    "Danish Black-Pied",
    "Danish Jersey",
    "Danish Red",
    "Dedit",
    "Deep Red cattle",
    "Deoni",
    "Devon",
    "Dexter cattle",
    "Dhanni",
    "Doayo cattle",
    "Doela",
    "Drakensberger",
    "Droughtmaster",
    "Dulong'",
    "Dutch Belted",
    "Dutch Friesian",
    "Dwarf Lulu",
    "Dølafe",
    "East Anatolian Red",
    "Eastern Finncattle",
    "Eastern Red Polled",
    "Eedit",
    "Enderby Island cattle",
    "English Longhorn",
    "Ennstaler Bergscheck",
    "Estonian Holstein",
    "Estonian Native",
    "Estonian Red cattle",
    "Fedit",
    "Finncattle",
    "Finnish Ayrshire",
    "Finnish Holstein-Friesian",
    "Fjäll",
    "Fleckvieh",
    "Florida Cracker cattle",
    "Fogera",
    "French Simmental",
    "Fribourgeoise",
    "Friesian Red and White",
    "Fulani Sudanese",
    "Fēng Cattle",
    "Galician Blond",
    "Galloway cattle",
    "Gangatiri",
    "Gaolao",
    "Garvonesa",
    "Gascon cattle",
    "Gedit",
    "Gelbvieh",
    "Georgian Mountain cattle",
    "German Angus",
    "German Black Pied Dairy",
    "German Black Pied cattle",
    "German Red Pied",
    "Gir",
    "Glan cattle",
    "Gloucester",
    "Gobra",
    "Greek Shorthorn",
    "Greek Steppe",
    "Greyman cattle",
    "Gudali",
    "Guernsey cattle",
    "Guzerá",
    "Hallikar4",
    "Hanwoo",
    "Hariana cattle",
    "Hartón del Valle",
    "Harzer Rotvieh",
    "Hays Converter",
    "Heck cattle",
    "Hedit",
    "Hereford",
    "Herens",
    "Highland cattle",
    "Hinterwald",
    "Holando-Argentino",
    "Holstein Friesian cattle",
    "Horro",
    "Hungarian Grey",
    "Huáng Cattle",
    "Hybridmaster",
    "Iberian cattle",
    "Icelandic",
    "Iedit",
    "Illawarra cattle",
    "Improved Red and White",
    "Indo-Brazilian",
    "Irish Moiled",
    "Israeli Holstein",
    "Israeli Red",
    "Istoben cattle",
    "Istrian cattle",
    "Jamaica Black",
    "Jamaica Hope",
    "Jamaica Red",
    "Japanese Brown",
    "Jarmelista",
    "Javari cattle",
    "Jedit",
    "Jersey cattle",
    "Jutland cattle",
    "Kabin Buri cattle",
    "Kalmyk cattle",
    "Kamphaeng Saen cattle",
    "Kangayam",
    "Kankrej",
    "Karan Swiss",
    "Kasaragod Dwarf cattle",
    "Kathiawadi",
    "Kazakh Whiteheaded",
    "Kedit",
    "Kenana cattle",
    "Kenkatha cattle",
    "Kerry cattle",
    "Kherigarh",
    "Khillari cattle",
    "Kholomogory",
    "Korat Wagyu",
    "Kostroma cattle",
    "Krishna Valley cattle",
    "Kurgan cattle",
    "Kuri",
    "La Reina cattle",
    "Lakenvelder cattle",
    "Lampurger",
    "Latvian Blue",
    "Latvian Brown",
    "Latvian Danish Red",
    "Lebedyn",
    "Ledit",
    "Levantina",
    "Limia cattle",
    "Limousin",
    "Limpurger",
    "Lincoln Red",
    "Lineback",
    "Lithuanian Black-and-White",
    "Lithuanian Light Grey",
    "Lithuanian Red",
    "Lithuanian White-Backed",
    "Lohani cattle",
    "Lourdais",
    "Lucerna cattle",
    "Luing",
    "Madagascar Zebu",
    "Madura",
    "Maine-Anjou",
    "Malnad Gidda",
    "Malvi",
    "Mandalong Special",
    "Mantequera Leonesa",
    "Maramureş Brown",
    "Marchigiana",
    "Maremmana",
    "Marinhoa",
    "Maronesa",
    "Masai",
    "Mashona",
    "Medit",
    "Menorquina",
    "Mertolenga",
    "Meuse-Rhine-Issel",
    "Mewati",
    "Milking Shorthorn",
    "Minhota",
    "Mirandesa",
    "Mirkadim",
    "Mocăniţă",
    "Mollie",
    "Monchina",
    "Mongolian",
    "Montbéliarde",
    "Morucha",
    "Murboden",
    "Murnau-Werdenfels",
    "Murray Grey",
    "Muturu",
    "N'Dama",
    "Nagori",
    "Nedit",
    "Negra Andaluza",
    "Nelore",
    "Nguni",
    "Nimari",
    "Normande",
    "North Bengal Grey",
    "Northern Finncattle",
    "Northern Shorthorn",
    "Norwegian Red",
    "Oedit]",
    "Ongole",
    "Original Simmental",
    "Pajuna",
    "Palmera",
    "Pantaneiro",
    "Parda Alpina",
    "Parthenaise",
    "Pasiega",
    "Pedit",
    "Pembroke",
    "Philippine Native",
    "Pie Rouge des Plaines",
    "Piedmontese cattle",
    "Pineywoods",
    "Pinzgauer",
    "Pirenaica",
    "Podolac",
    "Podolica",
    "Polish Black-and-White",
    "Polish Red",
    "Poll Shorthorn",
    "Polled Hereford",
    "Polled Shorthorn",
    "Ponwar",
    "Preta",
    "Pulikulam",
    "Punganur",
    "Pustertaler Sprinzen",
    "Qedit",
    "Qinchaun",
    "Queensland Miniature Boran",
    "RX3",
    "Ramo Grande",
    "Randall",
    "Raramuri Criollo",
    "Rathi",
    "Raya",
    "Red Angus",
    "Red Brangus",
    "Red Chittagong",
    "Red Fulani",
    "Red Gorbatov",
    "Red Holstein",
    "Red Kandhari",
    "Red Mingrelian",
    "Red Poll",
    "Red Polled Østland",
    "Red Sindhi",
    "Redit",
    "Retinta",
    "Riggit Galloway",
    "Ringamåla",
    "Rohjan",
    "Romagnola",
    "Romanian Bălţata",
    "Romanian Steppe Gray",
    "Romosinuano",
    "Russian Black Pied",
    "Rätisches Grauvieh",
    "Sahiwal",
    "Salers",
    "Salorn",
    "Sanga",
    "Sanhe",
    "Santa Cruz",
    "Santa Gertrudis",
    "Sayaguesa",
    "Schwyz",
    "Sedit",
    "Selembu",
    "Senepol",
    "Serbian Pied",
    "Serbian Steppe",
    "Sheko",
    "Shetland",
    "Shorthorn",
    "Siboney de Cuba",
    "Simbrah",
    "Simford",
    "Simmental",
    "Siri",
    "South Devon",
    "Spanish Fighting Bull",
    "Speckle Park",
    "Square Meater",
    "Sussex",
    "Swedish Friesian",
    "Swedish Polled",
    "Swedish Red Pied",
    "Swedish Red Polled",
    "Swedish Red-and-White",
    "Tabapuã",
    "Tarentaise",
    "Tasmanian Grey",
    "Tauros",
    "Tedit",
    "Telemark",
    "Texas Longhorn",
    "Texon",
    "Thai Black",
    "Thai Fighting Bull",
    "Thai Friesian",
    "Thai Milking Zebu",
    "Tharparkar",
    "Tswana",
    "Tudanca",
    "Tuli",
    "Tulim",
    "Turkish Grey Steppe",
    "Tux-Zillertal",
    "Tyrol Grey",
    "Uedit",
    "Ukrainian Grey",
    "Umblachery",
    "Valdostana Castana",
    "Valdostana Pezzata Nera",
    "Valdostana Pezzata Rossa",
    "Vaynol",
    "Vechur8",
    "Vedit",
    "Vestland Fjord",
    "Vestland Red Polled",
    "Vianesa",
    "Volinian Beef",
    "Vorderwald",
    "Vosgienne",
    "Väneko",
    "Waguli",
    "Wagyu",
    "Wangus",
    "Wedit",
    "Welsh Black",
    "Western Finncattle",
    "White Cáceres",
    "White Fulani",
    "White Lamphun",
    "White Park",
    "Whitebred Shorthorn",
    "Xedit",
    "Xingjiang Brown",
    "Yakutian",
    "Yanbian",
    "Yanhuang",
    "Yedit",
    "Yurino",
    "Zebu",
    "Zedit",
    "Évolène cattle",
    "Żubroń",
});

const auto enUSCrocodiles = std::to_array<std::string_view>({
    "African Slender-snouted Crocodile",
    "Alligator mississippiensis",
    "American Crocodile",
    "Australian Freshwater Crocodile",
    "Black Caiman",
    "Broad-snouted Caiman",
    "Chinese Alligator",
    "Cuban Crocodile",
    "Cuvier’s Dwarf Caiman",
    "Dwarf Crocodile",
    "Gharial",
    "Morelet’s Crocodile",
    "Mugger Crocodile",
    "New Guinea Freshwater Crocodile",
    "Nile Crocodile",
    "Orinoco Crocodile",
    "Philippine Crocodile",
    "Saltwater Crocodile",
    "Schneider’s Smooth-fronted Caiman",
    "Siamese Crocodile",
    "Spectacled Caiman",
    "Tomistoma",
    "West African Crocodile",
    "Yacare Caiman",
});

const auto enUSDogs = std::to_array<std::string_view>({
    "Affenpinscher",
    "Afghan Hound",
    "Aidi",
    "Airedale Terrier",
    "Akbash",
    "Akita",
    "Alano Español",
    "Alapaha Blue Blood Bulldog",
    "Alaskan Husky",
    "Alaskan Klee Kai",
    "Alaskan Malamute",
    "Alopekis",
    "Alpine Dachsbracke",
    "American Bulldog",
    "American Bully",
    "American Cocker Spaniel",
    "American English Coonhound",
    "American Foxhound",
    "American Hairless Terrier",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "American Water Spaniel",
    "Andalusian Hound",
    "Anglo-Français de Petite Vénerie",
    "Appenzeller Sennenhund",
    "Ariegeois",
    "Armant",
    "Armenian Gampr dog",
    "Artois Hound",
    "Australian Cattle Dog",
    "Australian Kelpie",
    "Australian Shepherd",
    "Australian Stumpy Tail Cattle Dog",
    "Australian Terrier",
    "Austrian Black and Tan Hound",
    "Austrian Pinscher",
    "Azawakh",
    "Bakharwal dog",
    "Banjara Hound",
    "Barbado da Terceira",
    "Barbet",
    "Basenji",
    "Basque Shepherd Dog",
    "Basset Artésien Normand",
    "Basset Bleu de Gascogne",
    "Basset Fauve de Bretagne",
    "Basset Hound",
    "Bavarian Mountain Hound",
    "Beagle",
    "Beagle-Harrier",
    "Bearded Collie",
    "Beauceron",
    "Bedlington Terrier",
    "Belgian Shepherd",
    "Bergamasco Shepherd",
    "Berger Picard",
    "Bernese Mountain Dog",
    "Bhotia",
    "Bichon Frisé",
    "Billy",
    "Black Mouth Cur",
    "Black Norwegian Elkhound",
    "Black Russian Terrier",
    "Black and Tan Coonhound",
    "Bloodhound",
    "Blue Lacy",
    "Blue Picardy Spaniel",
    "Bluetick Coonhound",
    "Boerboel",
    "Bohemian Shepherd",
    "Bolognese",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Bosnian Coarse-haired Hound",
    "Boston Terrier",
    "Bouvier des Ardennes",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Bracco Italiano",
    "Braque Francais",
    "Braque Saint-Germain",
    "Braque d'Auvergne",
    "Braque de l'Ariège",
    "Braque du Bourbonnais",
    "Briard",
    "Briquet Griffon Vendéen",
    "Brittany",
    "Broholmer",
    "Bruno Jura Hound",
    "Brussels Griffon",
    "Bucovina Shepherd Dog",
    "Bull Arab",
    "Bull Terrier",
    "Bulldog",
    "Bullmastiff",
    "Bully Kutta",
    "Burgos Pointer",
    "Cairn Terrier",
    "Campeiro Bulldog",
    "Can de Chira",
    "Canaan Dog",
    "Canadian Eskimo Dog",
    "Cane Corso",
    "Cane Paratore",
    "Cane di Oropa",
    "Cantabrian Water Dog",
    "Cardigan Welsh Corgi",
    "Carea Castellano Manchego",
    "Carolina Dog",
    "Carpathian Shepherd Dog",
    "Catahoula Leopard Dog",
    "Catalan Sheepdog",
    "Caucasian Shepherd Dog",
    "Cavalier King Charles Spaniel",
    "Central Asian Shepherd Dog",
    "Cesky Fousek",
    "Cesky Terrier",
    "Chesapeake Bay Retriever",
    "Chien Français Blanc et Noir",
    "Chien Français Blanc et Orange",
    "Chien Français Tricolore",
    "Chihuahua",
    "Chilean Terrier",
    "Chinese Chongqing Dog",
    "Chinese Crested Dog",
    "Chinook",
    "Chippiparai",
    "Chongqing dog",
    "Chortai",
    "Chow Chow",
    "Cimarrón Uruguayo",
    "Cirneco dell'Etna",
    "Clumber Spaniel",
    "Colombian fino hound",
    "Coton de Tulear",
    "Cretan Hound",
    "Croatian Sheepdog",
    "Curly-Coated Retriever",
    "Cursinu",
    "Czechoslovakian Wolfdog",
    "Cão Fila de São Miguel",
    "Cão da Serra de Aires",
    "Cão de Castro Laboreiro",
    "Cão de Gado Transmontano",
    "Dachshund",
    "Dalmatian",
    "Dandie Dinmont Terrier",
    "Danish-Swedish Farmdog",
    "Denmark Feist",
    "Dingo",
    "Doberman Pinscher",
    "Dogo Argentino",
    "Dogo Guatemalteco",
    "Dogo Sardesco",
    "Dogue Brasileiro",
    "Dogue de Bordeaux",
    "Drentse Patrijshond",
    "Drever",
    "Dunker",
    "Dutch Shepherd",
    "Dutch Smoushond",
    "East European Shepherd",
    "East Siberian Laika",
    "English Cocker Spaniel",
    "English Foxhound",
    "English Mastiff",
    "English Setter",
    "English Shepherd",
    "English Springer Spaniel",
    "English Toy Terrier",
    "Entlebucher Mountain Dog",
    "Estonian Hound",
    "Estrela Mountain Dog",
    "Eurasier",
    "Field Spaniel",
    "Fila Brasileiro",
    "Finnish Hound",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat-Coated Retriever",
    "French Bulldog",
    "French Spaniel",
    "Galgo Español",
    "Galician Shepherd Dog",
    "Garafian Shepherd",
    "Gascon Saintongeois",
    "Georgian Shepherd",
    "German Hound",
    "German Longhaired Pointer",
    "German Pinscher",
    "German Roughhaired Pointer",
    "German Shepherd Dog",
    "German Shorthaired Pointer",
    "German Spaniel",
    "German Spitz",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Golden Retriever",
    "Gordon Setter",
    "Gończy Polski",
    "Grand Anglo-Français Blanc et Noir",
    "Grand Anglo-Français Blanc et Orange",
    "Grand Anglo-Français Tricolore",
    "Grand Basset Griffon Vendéen",
    "Grand Bleu de Gascogne",
    "Grand Griffon Vendéen",
    "Great Dane",
    "Greater Swiss Mountain Dog",
    "Greek Harehound",
    "Greek Shepherd",
    "Greenland Dog",
    "Greyhound",
    "Griffon Bleu de Gascogne",
    "Griffon Fauve de Bretagne",
    "Griffon Nivernais",
    "Gull Dong",
    "Gull Terrier",
    "Hamiltonstövare",
    "Hanover Hound",
    "Harrier",
    "Havanese",
    "Hierran Wolfdog",
    "Hokkaido",
    "Hovawart",
    "Huntaway",
    "Hygen Hound",
    "Hällefors Elkhound",
    "Ibizan Hound",
    "Icelandic Sheepdog",
    "Indian Spitz",
    "Indian pariah dog",
    "Irish Red and White Setter",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Istrian Coarse-haired Hound",
    "Istrian Shorthaired Hound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Jagdterrier",
    "Japanese Chin",
    "Japanese Spitz",
    "Japanese Terrier",
    "Jindo",
    "Jonangi",
    "Kai Ken",
    "Kaikadi",
    "Kangal Shepherd Dog",
    "Kanni",
    "Karakachan dog",
    "Karelian Bear Dog",
    "Kars",
    "Karst Shepherd",
    "Keeshond",
    "Kerry Beagle",
    "Kerry Blue Terrier",
    "King Charles Spaniel",
    "King Shepherd",
    "Kintamani",
    "Kishu",
    "Kokoni",
    "Kombai",
    "Komondor",
    "Kooikerhondje",
    "Koolie",
    "Koyun dog",
    "Kromfohrländer",
    "Kuchi",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Landseer",
    "Lapponian Herder",
    "Large Münsterländer",
    "Leonberger",
    "Levriero Sardo",
    "Lhasa Apso",
    "Lithuanian Hound",
    "Lupo Italiano",
    "Löwchen",
    "Mackenzie River Husky",
    "Magyar agár",
    "Mahratta Greyhound",
    "Maltese",
    "Manchester Terrier",
    "Maremmano-Abruzzese Sheepdog",
    "McNab dog",
    "Miniature American Shepherd",
    "Miniature Bull Terrier",
    "Miniature Fox Terrier",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Molossus of Epirus",
    "Montenegrin Mountain Hound",
    "Mountain Cur",
    "Mountain Feist",
    "Mucuchies",
    "Mudhol Hound",
    "Mudi",
    "Neapolitan Mastiff",
    "New Guinea Singing Dog",
    "New Zealand Heading Dog",
    "Newfoundland",
    "Norfolk Terrier",
    "Norrbottenspets",
    "Northern Inuit Dog",
    "Norwegian Buhund",
    "Norwegian Elkhound",
    "Norwegian Lundehund",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old Croatian Sighthound",
    "Old Danish Pointer",
    "Old English Sheepdog",
    "Old English Terrier",
    "Olde English Bulldogge",
    "Otterhound",
    "Pachon Navarro",
    "Paisley Terrier",
    "Pampas Deerhound",
    "Papillon",
    "Parson Russell Terrier",
    "Pastore della Lessinia e del Lagorai",
    "Patagonian Sheepdog",
    "Patterdale Terrier",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Perro Majorero",
    "Perro de Pastor Mallorquin",
    "Perro de Presa Canario",
    "Perro de Presa Mallorquin",
    "Peruvian Inca Orchid",
    "Petit Basset Griffon Vendéen",
    "Petit Bleu de Gascogne",
    "Phalène",
    "Pharaoh Hound",
    "Phu Quoc Ridgeback",
    "Picardy Spaniel",
    "Plott Hound",
    "Plummer Terrier",
    "Podenco Canario",
    "Podenco Valenciano",
    "Pointer",
    "Poitevin",
    "Polish Greyhound",
    "Polish Hound",
    "Polish Lowland Sheepdog",
    "Polish Tatra Sheepdog",
    "Pomeranian",
    "Pont-Audemer Spaniel",
    "Poodle",
    "Porcelaine",
    "Portuguese Podengo",
    "Portuguese Pointer",
    "Portuguese Water Dog",
    "Posavac Hound",
    "Pražský Krysařík",
    "Pshdar Dog",
    "Pudelpointer",
    "Pug",
    "Puli",
    "Pumi",
    "Pungsan Dog",
    "Pyrenean Mastiff",
    "Pyrenean Mountain Dog",
    "Pyrenean Sheepdog",
    "Rafeiro do Alentejo",
    "Rajapalayam",
    "Rampur Greyhound",
    "Rat Terrier",
    "Ratonero Bodeguero Andaluz",
    "Ratonero Mallorquin",
    "Ratonero Murciano de Huerta",
    "Ratonero Valenciano",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Romanian Mioritic Shepherd Dog",
    "Romanian Raven Shepherd Dog",
    "Rottweiler",
    "Rough Collie",
    "Russian Spaniel",
    "Russian Toy",
    "Russo-European Laika",
    "Saarloos Wolfdog",
    "Sabueso Español",
    "Saint Bernard",
    "Saint Hubert Jura Hound",
    "Saint-Usuge Spaniel",
    "Saluki",
    "Samoyed",
    "Sapsali",
    "Sarabi dog",
    "Sardinian Shepherd Dog",
    "Schapendoes",
    "Schillerstövare",
    "Schipperke",
    "Schweizer Laufhund",
    "Schweizerischer Niederlaufhund",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Segugio Italiano",
    "Segugio Maremmano",
    "Segugio dell'Appennino",
    "Seppala Siberian Sleddog",
    "Serbian Hound",
    "Serbian Tricolour Hound",
    "Serrano Bulldog",
    "Shar Pei",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Shikoku",
    "Shiloh Shepherd",
    "Siberian Husky",
    "Silken Windhound",
    "Silky Terrier",
    "Sinhala Hound",
    "Skye Terrier",
    "Sloughi",
    "Slovakian Wirehaired Pointer",
    "Slovenský Cuvac",
    "Slovenský Kopov",
    "Smalandstövare",
    "Small Greek domestic dog",
    "Small Münsterländer",
    "Smooth Collie",
    "Smooth Fox Terrier",
    "Soft-Coated Wheaten Terrier",
    "South Russian Ovcharka",
    "Spanish Mastiff",
    "Spanish Water Dog",
    "Spinone Italiano",
    "Sporting Lucas Terrier",
    "Stabyhoun",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Stephens Stock",
    "Styrian Coarse-haired Hound",
    "Sussex Spaniel",
    "Swedish Elkhound",
    "Swedish Lapphund",
    "Swedish Vallhund",
    "Swedish White Elkhound",
    "Taigan",
    "Taiwan Dog",
    "Tamaskan Dog",
    "Teddy Roosevelt Terrier",
    "Telomian",
    "Tenterfield Terrier",
    "Terrier Brasileiro",
    "Thai Bangkaew Dog",
    "Thai Ridgeback",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Tornjak",
    "Tosa",
    "Toy Fox Terrier",
    "Toy Manchester Terrier",
    "Transylvanian Hound",
    "Treeing Cur",
    "Treeing Feist",
    "Treeing Tennessee Brindle",
    "Treeing Walker Coonhound",
    "Trigg Hound",
    "Tyrolean Hound",
    "Vikhan",
    "Villano de Las Encartaciones",
    "Villanuco de Las Encartaciones",
    "Vizsla",
    "Volpino Italiano",
    "Weimaraner",
    "Welsh Sheepdog",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "West Highland White Terrier",
    "West Siberian Laika",
    "Westphalian Dachsbracke",
    "Wetterhoun",
    "Whippet",
    "White Shepherd",
    "White Swiss Shepherd Dog",
    "Wire Fox Terrier",
    "Wirehaired Pointing Griffon",
    "Wirehaired Vizsla",
    "Xiasi Dog",
    "Xoloitzcuintli",
    "Yakutian Laika",
    "Yorkshire Terrier",
    "Šarplaninac",
});

const auto enUSFishes = std::to_array<std::string_view>({
    "Alaska pollock",
    "Albacore",
    "Amur catfish",
    "Araucanian herring",
    "Argentine hake",
    "Asari",
    "Asian swamp eel",
    "Atlantic cod",
    "Atlantic herring",
    "Atlantic horse mackerel",
    "Atlantic mackerel",
    "Atlantic menhaden",
    "Atlantic salmon",
    "Bigeye scad",
    "Bigeye tuna",
    "Bighead carp",
    "Black carp",
    "Blood cockle",
    "Blue swimming crab",
    "Blue whiting",
    "Bombay-duck",
    "Bonga shad",
    "California pilchard",
    "Cape horse mackerel",
    "Capelin",
    "Catla",
    "Channel catfish",
    "Chilean jack mackerel",
    "Chinese perch",
    "Chinese softshell turtle",
    "Chub mackerel",
    "Chum salmon",
    "Common carp",
    "Crucian carp",
    "Daggertooth pike conger",
    "European anchovy",
    "European pilchard",
    "European sprat",
    "Filipino Venus",
    "Gazami crab",
    "Goldstripe sardinella",
    "Grass carp",
    "Gulf menhaden",
    "Haddock",
    "Hilsa shad",
    "Indian mackerel",
    "Indian oil sardine",
    "Iridescent shark",
    "Japanese anchovy",
    "Japanese cockle",
    "Japanese common catfish",
    "Japanese flying squid",
    "Japanese jack mackerel",
    "Japanese littleneck",
    "Japanese pilchard",
    "Jumbo flying squid",
    "Kawakawa",
    "Korean bullhead",
    "Largehead hairtail",
    "Longtail tuna",
    "Madeiran sardinella",
    "Mandarin fish",
    "Milkfish",
    "Mrigal carp",
    "Narrow-barred Spanish mackerel",
    "Nile perch",
    "Nile tilapia",
    "North Pacific hake",
    "Northern snakehead",
    "Pacific anchoveta",
    "Pacific cod",
    "Pacific herring",
    "Pacific sand lance",
    "Pacific sandlance",
    "Pacific saury",
    "Pacific thread herring",
    "Peruvian anchoveta",
    "Pink salmon",
    "Pollock",
    "Pond loach",
    "Rainbow trout",
    "Rohu",
    "Round sardinella",
    "Short mackerel",
    "Silver carp",
    "Silver cyprinid",
    "Skipjack tuna",
    "Southern African anchovy",
    "Southern rough shrimp",
    "Whiteleg shrimp",
    "Wuchang bream",
    "Yellow croaker",
    "Yellowfin tuna",
    "Yellowhead catfish",
    "Yellowstripe scad",
});

const auto enUSHorses = std::to_array<std::string_view>({
    "Abaco Barb",
    "Abtenauer",
    "Abyssinian",
    "Aegidienberger",
    "Akhal-Teke",
    "Albanian Horse",
    "Altai Horse",
    "Altèr Real",
    "American Albino",
    "American Cream Draft",
    "American Indian Horse",
    "American Paint Horse",
    "American Quarter Horse",
    "American Saddlebred",
    "American Warmblood",
    "Andalusian Horse",
    "Andravida Horse",
    "Anglo-Arabian",
    "Anglo-Arabo-Sardo",
    "Anglo-Kabarda",
    "Appaloosa",
    "AraAppaloosa",
    "Arabian Horse",
    "Ardennes Horse",
    "Arenberg-Nordkirchen",
    "Argentine Criollo",
    "Asian wild Horse",
    "Assateague Horse",
    "Asturcón",
    "Augeron",
    "Australian Brumby",
    "Australian Draught Horse",
    "Australian Stock Horse",
    "Austrian Warmblood",
    "Auvergne Horse",
    "Auxois",
    "Azerbaijan Horse",
    "Azteca Horse",
    "Baise Horse",
    "Bale",
    "Balearic Horse",
    "Balikun Horse",
    "Baluchi Horse",
    "Banker Horse",
    "Barb Horse",
    "Bardigiano",
    "Bashkir Curly",
    "Basque Mountain Horse",
    "Bavarian Warmblood",
    "Belgian Half-blood",
    "Belgian Horse",
    "Belgian Warmblood ",
    "Bhutia Horse",
    "Black Forest Horse",
    "Blazer Horse",
    "Boerperd",
    "Borana",
    "Boulonnais Horse",
    "Brabant",
    "Brandenburger",
    "Brazilian Sport Horse",
    "Breton Horse",
    "Brumby",
    "Budyonny Horse",
    "Burguete Horse",
    "Burmese Horse",
    "Byelorussian Harness Horse",
    "Calabrese Horse",
    "Camargue Horse",
    "Camarillo White Horse",
    "Campeiro",
    "Campolina",
    "Canadian Horse",
    "Canadian Pacer",
    "Carolina Marsh Tacky",
    "Carthusian Horse",
    "Caspian Horse",
    "Castilian Horse",
    "Castillonnais",
    "Catria Horse",
    "Cavallo Romano della Maremma Laziale",
    "Cerbat Mustang",
    "Chickasaw Horse",
    "Chilean Corralero",
    "Choctaw Horse",
    "Cleveland Bay",
    "Clydesdale Horse",
    "Cob",
    "Coldblood Trotter",
    "Colonial Spanish Horse",
    "Colorado Ranger",
    "Comtois Horse",
    "Corsican Horse",
    "Costa Rican Saddle Horse",
    "Cretan Horse",
    "Criollo Horse",
    "Croatian Coldblood",
    "Cuban Criollo",
    "Cumberland Island Horse",
    "Curly Horse",
    "Czech Warmblood",
    "Daliboz",
    "Danish Warmblood",
    "Danube Delta Horse",
    "Dole Gudbrandsdal",
    "Don",
    "Dongola Horse",
    "Draft Trotter",
    "Dutch Harness Horse",
    "Dutch Heavy Draft",
    "Dutch Warmblood",
    "Dzungarian Horse",
    "East Bulgarian",
    "East Friesian Horse",
    "Estonian Draft",
    "Estonian Horse",
    "Falabella",
    "Faroese",
    "Finnhorse",
    "Fjord Horse",
    "Fleuve",
    "Florida Cracker Horse",
    "Foutanké",
    "Frederiksborg Horse",
    "Freiberger",
    "French Trotter",
    "Friesian Cross",
    "Friesian Horse",
    "Friesian Sporthorse",
    "Furioso-North Star",
    "Galiceño",
    "Galician Pony",
    "Gelderland Horse",
    "Georgian Grande Horse",
    "German Warmblood",
    "Giara Horse",
    "Gidran",
    "Groningen Horse",
    "Gypsy Horse",
    "Hackney Horse",
    "Haflinger",
    "Hanoverian Horse",
    "Heck Horse",
    "Heihe Horse",
    "Henson Horse",
    "Hequ Horse",
    "Hirzai",
    "Hispano-Bretón",
    "Holsteiner Horse",
    "Horro",
    "Hungarian Warmblood",
    "Icelandic Horse",
    "Iomud",
    "Irish Draught",
    "Irish Sport Horse sometimes called Irish Hunter",
    "Italian Heavy Draft",
    "Italian Trotter",
    "Jaca Navarra",
    "Jeju Horse",
    "Jutland Horse",
    "Kabarda Horse",
    "Kafa",
    "Kaimanawa Horses",
    "Kalmyk Horse",
    "Karabair",
    "Karabakh Horse",
    "Karachai Horse",
    "Karossier",
    "Kathiawari",
    "Kazakh Horse",
    "Kentucky Mountain Saddle Horse",
    "Kiger Mustang",
    "Kinsky Horse",
    "Kisber Felver",
    "Kiso Horse",
    "Kladruber",
    "Knabstrupper",
    "Konik",
    "Kundudo",
    "Kustanair",
    "Kyrgyz Horse",
    "Latvian Horse",
    "Lipizzan",
    "Lithuanian Heavy Draught",
    "Lokai",
    "Losino Horse",
    "Lusitano",
    "Lyngshest",
    "M'Bayar",
    "M'Par",
    "Mallorquín",
    "Malopolski",
    "Mangalarga",
    "Mangalarga Marchador",
    "Maremmano",
    "Marismeño Horse",
    "Marsh Tacky",
    "Marwari Horse",
    "Mecklenburger",
    "Menorquín",
    "Messara Horse",
    "Metis Trotter",
    "Mezőhegyesi Sport Horse",
    "Međimurje Horse",
    "Miniature Horse",
    "Misaki Horse",
    "Missouri Fox Trotter",
    "Monchina",
    "Mongolian Horse",
    "Mongolian Wild Horse",
    "Monterufolino",
    "Morab",
    "Morgan Horse",
    "Mountain Pleasure Horse",
    "Moyle Horse",
    "Murakoz Horse",
    "Murgese",
    "Mustang Horse",
    "Mérens Horse",
    "Namib Desert Horse",
    "Nangchen Horse",
    "National Show Horse",
    "Nez Perce Horse",
    "Nivernais Horse",
    "Nokota Horse",
    "Noma",
    "Nonius Horse",
    "Nooitgedachter",
    "Nordlandshest",
    "Noriker Horse",
    "Norman Cob",
    "North American Single-Footer Horse",
    "North Swedish Horse",
    "Norwegian Coldblood Trotter",
    "Norwegian Fjord",
    "Novokirghiz",
    "Oberlander Horse",
    "Ogaden",
    "Oldenburg Horse",
    "Orlov trotter",
    "Ostfriesen",
    "Paint",
    "Pampa Horse",
    "Paso Fino",
    "Pentro Horse",
    "Percheron",
    "Persano Horse",
    "Peruvian Paso",
    "Pintabian",
    "Pleven Horse",
    "Poitevin Horse",
    "Posavac Horse",
    "Pottok",
    "Pryor Mountain Mustang",
    "Przewalski's Horse",
    "Pura Raza Española",
    "Purosangue Orientale",
    "Qatgani",
    "Quarab",
    "Quarter Horse",
    "Racking Horse",
    "Retuerta Horse",
    "Rhenish German Coldblood",
    "Rhinelander Horse",
    "Riwoche Horse",
    "Rocky Mountain Horse",
    "Romanian Sporthorse",
    "Rottaler",
    "Russian Don",
    "Russian Heavy Draft",
    "Russian Trotter",
    "Saddlebred",
    "Salerno Horse",
    "Samolaco Horse",
    "San Fratello Horse",
    "Sarcidano Horse",
    "Sardinian Anglo-Arab",
    "Schleswig Coldblood",
    "Schwarzwälder Kaltblut",
    "Selale",
    "Sella Italiano",
    "Selle Français",
    "Shagya Arabian",
    "Shan Horse",
    "Shire Horse",
    "Siciliano Indigeno",
    "Silesian Horse",
    "Sokolsky Horse",
    "Sorraia",
    "South German Coldblood",
    "Soviet Heavy Draft",
    "Spanish Anglo-Arab",
    "Spanish Barb",
    "Spanish Jennet Horse",
    "Spanish Mustang",
    "Spanish Tarpan",
    "Spanish-Norman Horse",
    "Spiti Horse",
    "Spotted Saddle Horse",
    "Standardbred Horse",
    "Suffolk Punch",
    "Swedish Ardennes",
    "Swedish Warmblood",
    "Swedish coldblood trotter",
    "Swiss Warmblood",
    "Taishū Horse",
    "Takhi",
    "Tawleed",
    "Tchernomor",
    "Tennessee Walking Horse",
    "Tersk Horse",
    "Thoroughbred",
    "Tiger Horse",
    "Tinker Horse",
    "Tolfetano",
    "Tori Horse",
    "Trait Du Nord",
    "Trakehner",
    "Tsushima",
    "Tuigpaard",
    "Ukrainian Riding Horse",
    "Unmol Horse",
    "Uzunyayla",
    "Ventasso Horse",
    "Virginia Highlander",
    "Vlaamperd",
    "Vladimir Heavy Draft",
    "Vyatka",
    "Waler",
    "Waler Horse",
    "Walkaloosa",
    "Warlander",
    "Warmblood",
    "Welsh Cob",
    "Westphalian Horse",
    "Wielkopolski",
    "Württemberger",
    "Xilingol Horse",
    "Yakutian Horse",
    "Yili Horse",
    "Yonaguni Horse",
    "Zaniskari",
    "Zhemaichu",
    "Zweibrücker",
    "Žemaitukas",
});

const auto enUSInsects = std::to_array<std::string_view>({
    "Acacia-ants",
    "Acorn-plum gall",
    "Aerial yellowjacket",
    "Africanized honey bee",
    "Allegheny mound ant",
    "Almond stone wasp",
    "Ant",
    "Arboreal ant",
    "Argentine ant",
    "Asian paper wasp",
    "Baldfaced hornet",
    "Bee",
    "Bigheaded ant",
    "Black and yellow mud dauber",
    "Black carpenter ant",
    "Black imported fire ant",
    "Blue horntail woodwasp",
    "Blue orchard bee",
    "Braconid wasp",
    "Bumble bee",
    "Carpenter ant",
    "Carpenter wasp",
    "Chalcid wasp",
    "Cicada killer",
    "Citrus blackfly parasitoid",
    "Common paper wasp",
    "Crazy ant",
    "Cuckoo wasp",
    "Cynipid gall wasp",
    "Eastern Carpenter bee",
    "Eastern yellowjacket",
    "Elm sawfly",
    "Encyrtid wasp",
    "Erythrina gall wasp",
    "Eulophid wasp",
    "European hornet",
    "European imported fire ant",
    "False honey ant",
    "Fire ant",
    "Forest bachac",
    "Forest yellowjacket",
    "German yellowjacket",
    "Ghost ant",
    "Giant ichneumon wasp",
    "Giant resin bee",
    "Giant wood wasp",
    "Golden northern bumble bee",
    "Golden paper wasp",
    "Gouty oak gall",
    "Grass Carrying Wasp",
    "Great black wasp",
    "Great golden digger wasp",
    "Hackberry nipple gall parasitoid",
    "Honey bee",
    "Horned oak gall",
    "Horse guard wasp",
    "Hunting wasp",
    "Ichneumonid wasp",
    "Keyhole wasp",
    "Knopper gall",
    "Large garden bumble bee",
    "Large oak-apple gall",
    "Leafcutting bee",
    "Little fire ant",
    "Little yellow ant",
    "Long-horned bees",
    "Long-legged ant",
    "Macao paper wasp",
    "Mallow bee",
    "Marble gall",
    "Mossyrose gall wasp",
    "Mud-daubers",
    "Multiflora rose seed chalcid",
    "Oak apple gall wasp",
    "Oak rough bulletgall wasp",
    "Oak saucer gall",
    "Oak shoot sawfly",
    "Odorous house ant",
    "Orange-tailed bumble bee",
    "Orangetailed potter wasp",
    "Oriental chestnut gall wasp",
    "Paper wasp",
    "Pavement ant",
    "Pigeon tremex",
    "Pip gall wasp",
    "Prairie yellowjacket",
    "Pteromalid wasp",
    "Pyramid ant",
    "Raspberry Horntail",
    "Red ant",
    "Red carpenter ant",
    "Red harvester ant",
    "Red imported fire ant",
    "Red wasp",
    "Red wood ant",
    "Red-tailed wasp",
    "Reddish carpenter ant",
    "Rough harvester ant",
    "Sawfly parasitic wasp",
    "Scale parasitoid",
    "Silky ant",
    "Sirex woodwasp",
    "Siricid woodwasp",
    "Smaller yellow ant",
    "Southeastern blueberry bee",
    "Southern fire ant",
    "Southern yellowjacket",
    "Sphecid wasp",
    "Stony gall",
    "Sweat bee",
    "Texas leafcutting ant",
    "Tiphiid wasp",
    "Torymid wasp",
    "Tramp ant",
    "Valentine ant",
    "Velvet ant",
    "Vespid wasp",
    "Weevil parasitoid",
    "Western harvester ant",
    "Western paper wasp",
    "Western thatching ant",
    "Western yellowjacket",
    "White-horned horntail",
    "Willow shoot sawfly",
    "Woodwasp",
    "Wool sower gall maker",
    "Yellow Crazy Ant",
    "Yellow and black potter wasp",
    "Yellow-horned horntail",
});

const auto enUSLions = std::to_array<std::string_view>({
    "Asiatic Lion",
    "Barbary Lion",
    "Cape lion",
    "Masai Lion",
    "Northeast Congo Lion",
    "Transvaal lion",
    "West African Lion",
});

const auto enUSRabbits = std::to_array<std::string_view>({
    "American",
    "American Chinchilla",
    "American Fuzzy Lop",
    "American Sable",
    "Argente Brun",
    "Belgian Hare",
    "Beveren",
    "Blanc de Hotot",
    "Britannia Petite",
    "Californian",
    "Champagne D’Argent",
    "Checkered Giant",
    "Cinnamon",
    "Crème D’Argent",
    "Dutch",
    "Dwarf Hotot",
    "English Angora",
    "English Lop",
    "English Spot",
    "Flemish Giant",
    "Florida White",
    "French Angora",
    "French Lop",
    "Giant Angora",
    "Giant Chinchilla",
    "Harlequin",
    "Havana",
    "Himalayan",
    "Holland Lop",
    "Jersey Wooly",
    "Lilac",
    "Lionhead",
    "Mini Lop",
    "Mini Rex",
    "Mini Satin",
    "Netherland Dwarf",
    "New Zealand",
    "Palomino",
    "Polish",
    "Rex",
    "Rhinelander",
    "Satin",
    "Satin Angora",
    "Silver",
    "Silver Fox",
    "Silver Marten",
    "Standard Chinchilla",
    "Tan",
    "Thrianta",
});

const auto enUSRodents = std::to_array<std::string_view>({
    "Abrocoma",
    "Abrocoma schistacea",
    "Aconaemys",
    "Aconaemys porteri",
    "African brush-tailed porcupine",
    "Andean mountain cavy",
    "Argentine tuco-tuco",
    "Ashy chinchilla rat",
    "Asiatic brush-tailed porcupine",
    "Atherurus",
    "Azara's agouti",
    "Azara's tuco-tuco",
    "Bahia porcupine",
    "Bathyergus",
    "Bathyergus janetta",
    "Bathyergus suillus",
    "Bennett's chinchilla rat",
    "Bicolored-spined porcupine",
    "Black agouti",
    "Black dwarf porcupine",
    "Black-rumped agouti",
    "Black-tailed hairy dwarf porcupine",
    "Bolivian chinchilla rat",
    "Bolivian tuco-tuco",
    "Bonetto's tuco-tuco",
    "Brandt's yellow-toothed cavy",
    "Brazilian guinea pig",
    "Brazilian porcupine",
    "Brazilian tuco-tuco",
    "Bridge's degu",
    "Brown hairy dwarf porcupine",
    "Budin's chinchilla rat A. budini",
    "Cape porcupine",
    "Catamarca tuco-tuco",
    "Cavia",
    "Central American agouti",
    "Chacoan tuco-tuco",
    "Chilean rock rat",
    "Chinchilla",
    "Coendou",
    "Coiban agouti",
    "Colburn's tuco-tuco",
    "Collared tuco-tuco",
    "Common degu",
    "Common yellow-toothed cavy",
    "Conover's tuco-tuco",
    "Coruro",
    "Crested agouti",
    "Crested porcupine",
    "Cryptomys",
    "Cryptomys bocagei",
    "Cryptomys damarensis",
    "Cryptomys foxi",
    "Cryptomys hottentotus",
    "Cryptomys mechowi",
    "Cryptomys ochraceocinereus",
    "Cryptomys zechi",
    "Ctenomys",
    "Cuniculus",
    "Cuscomys",
    "Cuscomys ashanika",
    "Dactylomys",
    "Dactylomys boliviensis",
    "Dactylomys dactylinus",
    "Dactylomys peruanus",
    "Dasyprocta",
    "Domestic guinea pig",
    "Emily's tuco-tuco",
    "Erethizon",
    "Famatina chinchilla rat",
    "Frosted hairy dwarf porcupine",
    "Fukomys",
    "Fukomys amatus",
    "Fukomys anselli",
    "Fukomys bocagei",
    "Fukomys damarensis",
    "Fukomys darlingi",
    "Fukomys foxi",
    "Fukomys ilariae",
    "Fukomys kafuensis",
    "Fukomys mechowii",
    "Fukomys micklemi",
    "Fukomys occlusus",
    "Fukomys ochraceocinereus",
    "Fukomys whytei",
    "Fukomys zechi",
    "Furtive tuco-tuco",
    "Galea",
    "Georychus",
    "Georychus capensis",
    "Golden viscacha-rat",
    "Goya tuco-tuco",
    "Greater guinea pig",
    "Green acouchi",
    "Haig's tuco-tuco",
    "Heliophobius",
    "Heliophobius argenteocinereus",
    "Heterocephalus",
    "Heterocephalus glaber",
    "Highland tuco-tuco",
    "Hystrix",
    "Indian porcupine",
    "Isla Mocha degu",
    "Kalinowski agouti",
    "Kannabateomys",
    "Kannabateomys amblyonyx",
    "Lagidium",
    "Lagostomus",
    "Lewis' tuco-tuco",
    "Long-tailed chinchilla",
    "Long-tailed porcupine",
    "Los Chalchaleros' viscacha-rat",
    "Lowland paca",
    "Magellanic tuco-tuco",
    "Malayan porcupine",
    "Maule tuco-tuco",
    "Mendoza tuco-tuco",
    "Mexican agouti",
    "Mexican hairy dwarf porcupine",
    "Microcavia",
    "Montane guinea pig",
    "Moon-toothed degu",
    "Mottled tuco-tuco",
    "Mountain degu",
    "Mountain paca",
    "Mountain viscacha-rat",
    "Myoprocta",
    "Natterer's tuco-tuco",
    "North American porcupine",
    "Northern viscacha",
    "Octodon",
    "Octodontomys",
    "Octomys",
    "Olallamys",
    "Olallamys albicauda",
    "Olallamys edax",
    "Orinoco agouti",
    "Paraguaian hairy dwarf porcupine",
    "Pearson's tuco-tuco",
    "Peruvian tuco-tuco",
    "Philippine porcupine",
    "Pipanacoctomys",
    "Plains viscacha",
    "Plains viscacha-rat",
    "Porteous' tuco-tuco",
    "Punta de Vacas chinchilla rat",
    "Red acouchi",
    "Red-rumped agouti",
    "Reddish tuco-tuco",
    "Rio Negro tuco-tuco",
    "Robust tuco-tuco",
    "Roosmalen's dwarf porcupine",
    "Rothschild's porcupine",
    "Ruatan Island agouti",
    "Sage's rock rat",
    "Salinoctomys",
    "Salta tuco-tuco",
    "San Luis tuco-tuco",
    "Santa Catarina's guinea pig",
    "Shiny guinea pig",
    "Shipton's mountain cavy",
    "Short-tailed chinchilla",
    "Silky tuco-tuco",
    "Social tuco-tuco",
    "Southern mountain cavy",
    "Southern tuco-tuco",
    "Southern viscacha",
    "Spalacopus",
    "Spix's yellow-toothed cavy",
    "Steinbach's tuco-tuco",
    "Streaked dwarf porcupine",
    "Strong tuco-tuco",
    "Stump-tailed porcupine",
    "Sumatran porcupine",
    "Sunda porcupine",
    "Talas tuco-tuco",
    "Tawny tuco-tuco",
    "Thick-spined porcupine",
    "Tiny tuco-tuco",
    "Trichys",
    "Tucuman tuco-tuco",
    "Tympanoctomys",
    "Uspallata chinchilla rat",
    "White-toothed tuco-tuco",
    "Wolffsohn's viscacha",
});

const auto enUSSnakes = std::to_array<std::string_view>({
    "Abaco Island boa",
    "Aesculapian snake",
    "African beaked snake",
    "African puff adder",
    "African rock python",
    "African twig snake",
    "African wolf snake",
    "Amazon tree boa",
    "Amazonian palm viper",
    "American Vine Snake",
    "American copperhead",
    "Amethystine python",
    "Anaconda",
    "Andaman cat snake",
    "Andaman cobra",
    "Angolan python",
    "Annulated sea snake",
    "Arabian cobra",
    "Arafura file snake",
    "Arizona black rattlesnake",
    "Arizona coral snake",
    "Aruba rattlesnake",
    "Asian Vine Snake Whip Snake",
    "Asian cobra",
    "Asian keelback",
    "Asian pipe snake",
    "Asp",
    "Asp viper",
    "Assam keelback",
    "Australian copperhead",
    "Australian scrub python",
    "Baird's rat snake",
    "Baja California lyresnake",
    "Ball Python",
    "Ball python",
    "Bamboo pitviper",
    "Bamboo viper",
    "Banded Flying Snake",
    "Banded cat-eyed snake",
    "Banded krait",
    "Banded pitviper",
    "Banded water cobra",
    "Barbour's pit viper",
    "Barred wolf snake",
    "Beaked sea snake",
    "Beauty rat snake",
    "Beddome's cat snake",
    "Beddome's coral snake",
    "Bimini racer",
    "Bird snake",
    "Bismarck ringed python",
    "Black headed python",
    "Black krait",
    "Black mamba",
    "Black rat snake",
    "Black snake",
    "Black tree cobra",
    "Black-banded trinket snake",
    "Black-headed snake",
    "Black-necked cobra",
    "Black-necked spitting cobra",
    "Black-speckled palm-pitviper",
    "Black-striped keelback",
    "Black-tailed horned pit viper",
    "Blanding's tree snake",
    "Blind snake",
    "Blonde hognose snake",
    "Blood python",
    "Blue krait",
    "Blunt-headed tree snake",
    "Bluntnose viper",
    "Boa",
    "Boa constrictor",
    "Bocourt's water snake",
    "Boelen python",
    "Boiga",
    "Bolivian anaconda",
    "Boomslang",
    "Bornean pitviper",
    "Borneo short-tailed python",
    "Brahminy blind snake",
    "Brazilian coral snake",
    "Brazilian mud Viper",
    "Brazilian smooth snake",
    "Bredl's python",
    "Brongersma's pitviper",
    "Brown snake",
    "Brown spotted pitviper[4]",
    "Brown tree snake",
    "Brown water python",
    "Brown white-lipped python",
    "Buff striped keelback",
    "Bull snake",
    "Burmese keelback",
    "Burmese krait",
    "Burmese python",
    "Burrowing cobra",
    "Burrowing viper",
    "Bush viper",
    "Bushmaster",
    "Buttermilk racer",
    "Calabar python",
    "California kingsnake",
    "Canebrake",
    "Cantil",
    "Cantor's pitviper",
    "Cape cobra",
    "Cape coral snake",
    "Cape gopher snake",
    "Carpet viper",
    "Cascabel",
    "Caspian cobra",
    "Cat snake",
    "Cat-eyed night snake",
    "Cat-eyed snake",
    "Central American lyre snake",
    "Central ranges taipan",
    "Centralian carpet python",
    "Ceylon krait",
    "Chappell Island tiger snake",
    "Checkered garter snake",
    "Checkered keelback",
    "Chicken snake",
    "Chihuahuan ridge-nosed rattlesnake",
    "Children's python",
    "Chinese tree viper",
    "Coachwhip snake",
    "Coastal carpet python",
    "Coastal taipan",
    "Cobra",
    "Collett's snake",
    "Colorado desert sidewinder",
    "Common adder",
    "Common cobra",
    "Common garter snake",
    "Common ground snake",
    "Common keelback",
    "Common lancehead",
    "Common tiger snake",
    "Common worm snake",
    "Congo snake",
    "Congo water cobra",
    "Copperhead",
    "Coral snake",
    "Corn snake",
    "Coronado Island rattlesnake",
    "Cottonmouth",
    "Crossed viper",
    "Crowned snake",
    "Cuban boa",
    "Cuban wood snake",
    "Cyclades blunt-nosed viper",
    "Dauan Island water python",
    "De Schauensee's anaconda",
    "Death Adder",
    "Desert death adder",
    "Desert kingsnake",
    "Desert woma python",
    "Diamond python",
    "Dog-toothed cat snake",
    "Down's tiger snake",
    "Dubois's sea snake",
    "Dumeril's boa",
    "Durango rock rattlesnake",
    "Dusky pigmy rattlesnake",
    "Dusty hognose snake",
    "Dwarf beaked snake",
    "Dwarf boa",
    "Dwarf pipe snake",
    "Dwarf sand adder",
    "Eastern brown snake",
    "Eastern coral snake",
    "Eastern diamondback rattlesnake",
    "Eastern green mamba",
    "Eastern hognose snake",
    "Eastern lyre snake",
    "Eastern mud snake",
    "Eastern racer",
    "Eastern tiger snake",
    "Eastern water cobra",
    "Eastern yellowbelly sad racer",
    "Egg-eater",
    "Egyptian asp",
    "Egyptian cobra",
    "Elegant pitviper",
    "Emerald tree boa",
    "Equatorial spitting cobra",
    "European asp",
    "European smooth snake",
    "Eyelash palm-pitviper",
    "Eyelash pit viper",
    "Eyelash viper",
    "False cobra",
    "False horned viper",
    "False water cobra",
    "Fan-Si-Pan horned pitviper",
    "Fea's viper",
    "Fer-de-lance",
    "Fierce snake",
    "Fifty pacer",
    "Fishing snake",
    "Flat-nosed pitviper",
    "Flinders python",
    "Flying snake",
    "Forest cobra",
    "Forest flame snake",
    "Forsten's cat snake",
    "Fox snake three species of Pantherophis",
    "Gaboon viper",
    "Garter snake",
    "Giant Malagasy hognose snake",
    "Godman's pit viper",
    "Gold tree cobra",
    "Gold-ringed cat snake",
    "Golden tree snake",
    "Grand Canyon rattlesnake",
    "Grass snake",
    "Gray cat snake",
    "Great Basin rattlesnake",
    "Great Lakes bush viper",
    "Great Plains rat snake",
    "Green anaconda",
    "Green cat-eyed snake",
    "Green mamba",
    "Green palm viper",
    "Green rat snake",
    "Green snake",
    "Green tree pit viper",
    "Green tree python",
    "Grey Lora",
    "Grey-banded kingsnake",
    "Ground snake",
    "Guatemalan palm viper",
    "Guatemalan tree viper",
    "Habu",
    "Habu pit viper",
    "Hagen's pitviper",
    "Hairy bush viper",
    "Halmahera python",
    "Hardwicke's sea snake",
    "Harlequin coral snake",
    "High Woods coral snake",
    "Hill keelback",
    "Himalayan keelback",
    "Hogg Island boa",
    "Hognose snake",
    "Hognosed viper",
    "Honduran palm viper",
    "Hook Nosed Sea Snake",
    "Hopi rattlesnake",
    "Horned adder",
    "Horned desert viper",
    "Horned viper",
    "Horseshoe pitviper",
    "Hundred pacer",
    "Hutton's tree viper",
    "Ikaheka snake",
    "Indian cobra",
    "Indian flying snake",
    "Indian krait",
    "Indian python",
    "Indian tree viper",
    "Indigo snake",
    "Indochinese spitting cobra",
    "Indonesian water python",
    "Inland carpet python",
    "Inland taipan",
    "Jamaican Tree Snake",
    "Jamaican boa",
    "Jan's hognose snake",
    "Japanese forest rat snake",
    "Japanese rat snake",
    "Japanese striped snake",
    "Javan spitting cobra",
    "Jerdon's pitviper",
    "Jumping viper",
    "Jungle carpet python",
    "Kanburian pit viper",
    "Kaulback's lance-headed pitviper",
    "Kayaudi dwarf reticulated python",
    "Kaznakov's viper",
    "Keelback",
    "Kham Plateau pitviper",
    "Khasi Hills keelback",
    "King Island tiger snake",
    "King brown",
    "King cobra",
    "King rat snake",
    "King snake",
    "Krait",
    "Krefft's tiger snake",
    "Lance-headed rattlesnake",
    "Lancehead",
    "Large shield snake",
    "Large-eyed pitviper",
    "Large-scaled tree viper",
    "Leaf viper",
    "Leaf-nosed viper",
    "Lesser black krait",
    "Levant viper",
    "Long-nosed adder",
    "Long-nosed tree snake",
    "Long-nosed viper",
    "Long-nosed whip snake",
    "Long-tailed rattlesnake",
    "Longnosed worm snake",
    "Lora",
    "Lyre snake",
    "Machete savane",
    "Macklot's python",
    "Madagascar ground boa",
    "Madagascar tree boa",
    "Malabar rock pitviper",
    "Malayan krait",
    "Malayan long-glanded coral snake",
    "Malayan pit viper",
    "Malcolm's tree viper",
    "Mamba",
    "Mamushi",
    "Manchurian Black Water Snake",
    "Mandalay cobra",
    "Mandarin rat snake",
    "Mangrove pit viper",
    "Mangrove snake",
    "Mangshan pitviper",
    "Many-banded krait",
    "Many-banded tree snake",
    "Many-horned adder",
    "Many-spotted cat snake",
    "Massasauga rattlesnake",
    "McMahon's viper",
    "Mexican black kingsnake",
    "Mexican green rattlesnake",
    "Mexican hognose snake",
    "Mexican palm-pitviper",
    "Mexican parrot snake",
    "Mexican racer",
    "Mexican vine snake",
    "Mexican west coast rattlesnake",
    "Midget faded rattlesnake",
    "Milk snake",
    "Moccasin snake",
    "Modest keelback",
    "Mojave desert sidewinder",
    "Mojave rattlesnake",
    "Mole viper",
    "Mollucan python",
    "Moluccan flying snake",
    "Montpellier snake",
    "Motuo bamboo pitviper",
    "Mountain adder",
    "Mozambique spitting cobra",
    "Mud adder",
    "Mud snake",
    "Mussurana",
    "Namaqua dwarf adder",
    "Namib dwarf sand adder",
    "Narrowhead Garter Snake",
    "New Guinea carpet python",
    "Nichell snake",
    "Nicobar Island keelback",
    "Nicobar bamboo pitviper",
    "Night snake",
    "Nightingale adder",
    "Nilgiri keelback",
    "Nitsche's bush viper",
    "Nitsche's tree viper",
    "North Philippine cobra",
    "North eastern king snake",
    "Northeastern hill krait",
    "Northern black-tailed rattlesnake",
    "Northern tree snake",
    "Northern water snake",
    "Northern white-lipped python",
    "Northwestern carpet python",
    "Nose-horned viper",
    "Nubian spitting cobra",
    "Oaxacan small-headed rattlesnake",
    "Oenpelli python",
    "Olive python",
    "Olive sea snake",
    "Orange-collared keelback",
    "Ornate flying snake",
    "Palestine viper",
    "Pallas' viper",
    "Palm viper",
    "Papuan python",
    "Paradise flying snake",
    "Parrot snake",
    "Patchnose snake",
    "Paupan taipan",
    "Pelagic sea snake",
    "Peninsula tiger snake",
    "Peringuey's adder",
    "Perrotet's shieldtail snake",
    "Persian rat snake",
    "Philippine cobra",
    "Philippine pitviper",
    "Pine snake",
    "Pipe snake",
    "Pit viper",
    "Pointed-scaled pit viper[5]",
    "Pope's tree viper",
    "Portuguese viper",
    "Prairie kingsnake",
    "Puerto Rican boa",
    "Puff adder",
    "Pygmy python",
    "Python",
    "Queen snake",
    "Racer",
    "Raddysnake",
    "Rainbow boa",
    "Rat snake",
    "Rattler",
    "Rattlesnake",
    "Red blood python",
    "Red diamond rattlesnake",
    "Red spitting cobra",
    "Red-backed rat snake",
    "Red-bellied black snake",
    "Red-headed krait",
    "Red-necked keelback",
    "Red-tailed bamboo pitviper",
    "Red-tailed boa",
    "Red-tailed pipe snake",
    "Reticulated python",
    "Rhinoceros viper",
    "Rhombic night adder",
    "Ribbon snake",
    "Rinkhals",
    "Rinkhals cobra",
    "River jack",
    "Rosy boa",
    "Rough green snake",
    "Rough-scaled bush viper",
    "Rough-scaled python",
    "Rough-scaled tree viper",
    "Royal python",
    "Rubber boa",
    "Rufous beaked snake",
    "Rungwe tree viper",
    "San Francisco garter snake",
    "Sand adder",
    "Sand boa",
    "Savu python",
    "Saw-scaled viper",
    "Scarlet kingsnake",
    "Schlegel's viper",
    "Schultze's pitviper",
    "Sea snake",
    "Sedge viper",
    "Selayer reticulated python",
    "Sharp-nosed viper",
    "Shield-nosed cobra",
    "Shield-tailed snake",
    "Siamese palm viper",
    "Side-striped palm-pitviper",
    "Sidewinder",
    "Sikkim keelback",
    "Sinai desert cobra",
    "Sind krait",
    "Small-eyed snake",
    "Smooth green snake",
    "Smooth snake",
    "Snorkel viper",
    "Snouted cobra",
    "Sonoran sidewinder",
    "South American hognose snake",
    "South eastern corn snake",
    "Southern Indonesian spitting cobra",
    "Southern Pacific rattlesnake",
    "Southern Philippine cobra",
    "Southern black racer",
    "Southern white-lipped python",
    "Southwestern black spitting cobra",
    "Southwestern blackhead snake",
    "Southwestern carpet python",
    "Southwestern speckled rattlesnake",
    "Speckle-bellied keelback",
    "Speckled kingsnake",
    "Spectacled cobra",
    "Spiny bush viper",
    "Spitting cobra",
    "Spotted python",
    "Sri Lankan pit viper",
    "Stejneger's bamboo pitviper",
    "Stiletto snake",
    "Stimson's python",
    "Stoke's sea snake",
    "Storm water cobra",
    "Striped snake",
    "Sumatran short-tailed python",
    "Sumatran tree viper",
    "Sunbeam snake",
    "Taipan",
    "Taiwan cobra",
    "Tan racer",
    "Tancitaran dusky rattlesnake",
    "Tanimbar python",
    "Tasmanian tiger snake",
    "Tawny cat snake",
    "Temple pit viper",
    "Temple viper",
    "Tentacled snake",
    "Texas Coral Snake",
    "Texas blind snake",
    "Texas garter snake",
    "Texas lyre snake",
    "Texas night snake",
    "Thai cobra",
    "Three-lined ground snake",
    "Tibetan bamboo pitviper",
    "Tic polonga",
    "Tiger pit viper",
    "Tiger rattlesnake",
    "Tiger snake",
    "Tigre snake",
    "Timber rattlesnake",
    "Timor python",
    "Titanboa",
    "Tree boa",
    "Tree snake",
    "Tree viper",
    "Trinket snake",
    "Tropical rattlesnake",
    "Twig snake",
    "Twin Headed King Snake",
    "Twin-Barred tree snake",
    "Twin-spotted rat snake",
    "Twin-spotted rattlesnake",
    "Undulated pit viper",
    "Uracoan rattlesnake",
    "Ursini's viper",
    "Urutu",
    "Vine snake",
    "Viper",
    "Viper Adder",
    "Vipera ammodytes",
    "Wagler's pit viper",
    "Wart snake",
    "Water adder",
    "Water moccasin",
    "Water snake",
    "West Indian racer",
    "Western blind snake",
    "Western carpet python",
    "Western coral snake",
    "Western diamondback rattlesnake",
    "Western green mamba",
    "Western ground snake",
    "Western hog-nosed viper",
    "Western mud snake",
    "Western tiger snake",
    "Western woma python",
    "Wetar Island python",
    "Whip snake",
    "White-lipped keelback",
    "White-lipped python",
    "White-lipped tree viper",
    "Wirot's pit viper",
    "Wolf snake",
    "Woma python",
    "Worm snake",
    "Wutu",
    "Wynaad keelback",
    "Yarara",
    "Yellow anaconda",
    "Yellow-banded sea snake",
    "Yellow-bellied sea snake",
    "Yellow-lined palm viper",
    "Yellow-lipped sea snake",
    "Yellow-striped rat snake",
    "Yunnan keelback",
    "Zebra snake",
    "Zebra spitting cobra",
});

const auto enUSTypes = std::to_array<std::string_view>({
    "bear",
    "bird",
    "cat",
    "cetacean",
    "cow",
    "crocodilia",
    "dog",
    "fish",
    "horse",
    "insect",
    "lion",
    "rabbit",
    "snake",
});

const AnimalDefinition enUSAnimalDefinition = {
    .bears = enUSBears,
    .birds = enUSBirds,
    .cats = enUSCats,
    .cetaceans = enUSCetaceans,
    .cows = enUSCows,
    .crocodiles = enUSCrocodiles,
    .dogs = enUSDogs,
    .fishes = enUSFishes,
    .horses = enUSHorses,
    .insects = enUSInsects,
    .lions = enUSLions,
    .rabbits = enUSRabbits,
    .rodents = enUSRodents,
    .snakes = enUSSnakes,
    .types = enUSTypes,
};

}
