#include "medicine_data.h"

namespace faker::medicine::data {
const std::array<std::string_view, 59> medicalConditions = {
    "AIDS",
    "Anorexia Nervosa",
    "Arthritis, Juvenile Rheumatoid",
    "Asthma, Moderate or Severe Persistent",
    "Bronchiolitis",
    "Bulimia",
    "Cancer",
    "Cardiorespiratory Diseases",
    "Celiac Disease",
    "Cerebral Palsy",
    "Cleft Lip or Palate",
    "Crohn’s Disease",
    "Cystic Fibrosis",
    "Depression",
    "Developmental, Sensory, or Motor Disabilities",
    "Diabetes Mellitus",
    "Down syndrome",
    "Elevated Blood Lead Level",
    "Epilepsy",
    "Failure to Thrive",
    "Fetal Alcohol Syndrome",
    "Gall Bladder Disease",
    "Gastro Esophageal Reflux Disease",
    "Gastrointestinal Abnormalities",
    "HIV Infection",
    "Heart Disease",
    "Hepatitis",
    "Hypertension, Chronic/Prehypertension",
    "Hypertension, Pregnancy-induced",
    "Hyperthyroidism",
    "Hypoglycemia",
    "Hypothyroidism",
    "Inborn Errors of Metabolism",
    "Inflammatory Bowel Disease (IBD)",
    "Lactose Intolerance",
    "Large for Gestational Age",
    "Liver Disease",
    "Lupus Erythematosus",
    "Major Surgery, Burns, or Trauma",
    "Malabsorption Syndromes",
    "Meningitis",
    "Multiple Sclerosis",
    "Muscular Dystrophy",
    "Neonatal Abstinence Syndrome",
    "Neural Tube Defect (Spina Bifida)",
    "Nutrient Deficiency Diseases",
    "Pancreatitis",
    "Parasitic Infection",
    "Parkinson’s disease",
    "Pneumonia",
    "Prediabetes",
    "Renal Disease",
    "Sickle Cell Anemia",
    "Small Bowel Enterocolitis and syndrome",
    "Small for Gestational Age (SGA)",
    "Thalassemia Major",
    "Tuberculosis",
    "Ulcerative Colitis",
    "Ulcers, Stomach or Intestinal",
};

const std::array<std::string_view, 35> medicalTests = {
    "abdominal palpation",
    "cardiac auscultation",
    "HEENT examination",
    "digital rectal examination",
    "neurological examination",
    "psychiatric assessment",
    "pulmonary auscultation",
    "vaginal examination",
    "coronary catheterization",
    "echocardiography",
    "electrocardiogram",
    "ballistocardiogram",
    "skin biopsy",
    "hearing test",
    "laryngoscopy",
    "capsule endoscopy",
    "coloscopy",
    "endoscopic retrograde cholangiopancreatography",
    "esophagogastroduodenoscopy",
    "esophageal motility study",
    "esophageal pH monitoring",
    "liver biopsy",
    "electroencephalogram",
    "electromyography",
    "neuropsychological tests",
    "amniocentesis",
    "colposcopy",
    "mammography",
    "hysteroscopy",
    "laparoscopy",
    "polysomnography",
    "pulmonary plethysmography",
    "thoracentesis",
    "cystoscopy",
    "urodynamic testing",
};

const std::array<std::string_view, 55> specialties = {
    "Accident and emergency medicine",
    "Allergist",
    "Anaesthetics",
    "Cardiology",
    "Child psychiatry",
    "Clinical biology",
    "Clinical chemistry",
    "Clinical microbiology",
    "Clinical neurophysiology",
    "Craniofacial surgery",
    "Dermatology",
    "Endocrinology",
    "Family and General Medicine",
    "Gastroenterologic surgery",
    "Gastroenterology",
    "General Practice",
    "General surgery",
    "Geriatrics",
    "Hematology",
    "Immunology",
    "Infectious diseases",
    "Internal medicine",
    "Laboratory medicine",
    "Nephrology",
    "Neuropsychiatry",
    "Neurology",
    "Neurosurgery",
    "Nuclear medicine",
    "Obstetrics and gynaecology",
    "Occupational medicine",
    "Oncology",
    "Ophthalmology",
    "Oral and maxillofacial surgery",
    "Orthopaedics",
    "Otorhinolaryngology",
    "Paediatric surgery",
    "Paediatrics",
    "Pathology",
    "Pharmacology",
    "Physical medicine and rehabilitation",
    "Plastic surgery",
    "Podiatric surgery",
    "Preventive medicine",
    "Psychiatry",
    "Public health",
    "Radiation Oncology",
    "Radiology",
    "Respiratory medicine",
    "Rheumatology",
    "Stomatology",
    "Thoracic surgery",
    "Tropical medicine",
    "Urology",
    "Vascular surgery",
    "Venereology",
};
}
