#include "MusicData.h"

namespace faker::music
{
const std::array<std::string_view, 298> artists = {
    "2 Pac",
    "AC/DC",
    "Abba",
    "Adele",
    "Aerosmith",
    "Al Green",
    "Al Jolson",
    "Alabama",
    "Allman Brothers Band",
    "Andrews Sisters",
    "Aretha Franklin",
    "Art Blakey",
    "Art Tatum",
    "Artie Shaw",
    "B.B. King",
    "Barbra Streisand",
    "Barry White",
    "Beach Boys",
    "Beastie Boys",
    "Beatles",
    "Bee Gees",
    "Benny Goodman",
    "Bessie Smith",
    "Beyoncé",
    "Big Bill Broonzy",
    "Big Joe Turner",
    "Bill Evans",
    "Bill Haley and the Comets",
    "Bill Monroe",
    "Billie Holiday",
    "Billy Eckstine",
    "Billy Joel",
    "Billy Murray and the American Quartet",
    "Billy Ward and The Dominoes",
    "Bing Crosby",
    "Blondie",
    "Bo Diddley",
    "Bob Dylan",
    "Bob Marley and the Wailers",
    "Bob Wills and the Texas Playboys",
    "Bobby Darin",
    "Bon Jovi",
    "Brenda Lee",
    "Britney Spears",
    "Bruce Springsteen",
    "Buck Owens",
    "Buddy Holly and the Crickets",
    "Byrds",
    "Cab Calloway",
    "Carole King",
    "Carpenters",
    "Carter Family",
    "Celine Dion",
    "Charles Brown",
    "Charles Mingus",
    "Charley Patton",
    "Charlie Parker",
    "Chicago",
    "Chuck Berry",
    "Clara Ward Singers",
    "Clovers",
    "Coldplay",
    "Coleman Hawkins",
    "Connie Francis",
    "Conway Twitty",
    "Count Basie",
    "Crosby, Stills and Nash",
    "Curtis Mayfield and the Impressions",
    "Daryl Hall & John Oates",
    "David Bowie",
    "Dean Martin",
    "Deep Purple",
    "Dells",
    "Diana Ross and the Supremes",
    "Dinah Washington",
    "Dionne Warwick",
    "Dizzy Gillespie",
    "Dolly Parton",
    "Donna Summer",
    "Doors",
    "Dr. Dre",
    "Drake",
    "Drifters / Clyde McPhatter / Ben E. King",
    "Duke Ellington",
    "Eagles",
    "Earth, Wind and Fire",
    "Ed Sheeran",
    "Eddy Arnold",
    "Ella Fitzgerald",
    "Elmore James",
    "Elton John",
    "Elvis Costello",
    "Elvis Presley",
    "Emerson, Lake and Palmer",
    "Eminem",
    "Enrico Caruso",
    "Eric B. and Rakim",
    "Eric Clapton (solo and with bands)",
    "Ernest Tubb",
    "Ethel Waters",
    "Etta James",
    "Everly Brothers",
    "Fats Domino",
    "Fats Waller",
    "Fleetwood Mac",
    "Four Tops",
    "Frank Sinatra",
    "Frank Zappa / Mothers Of Invention",
    "Frankie Laine",
    "Frankie Valli and the Four Seasons",
    "Garth Brooks",
    "Gene Autry",
    "Genesis / Phil Collins",
    "George Clinton / Parliament / Funkadelic",
    "George Jones",
    "Gladys Knight and the Pips",
    "Glen Campbell",
    "Glenn Miller",
    "Grandmaster Flash and the Furious Five",
    "Grateful Dead",
    "Green Day",
    "Guns N' Roses",
    "Guy Lombardo",
    "Hank Snow",
    "Hank Williams",
    "Harry Belafonte",
    "Harry James",
    "Henry Burr and the Peerless Quartet",
    "Henry Mancini",
    "Herb Alpert and the Tijuana Brass",
    "Herbie Hancock",
    "Howlin' Wolf",
    "Ike & Tina Turner",
    "Ink Spots",
    "Iron Maiden",
    "Isley Brothers",
    "Jackie Wilson",
    "James Brown",
    "Janet Jackson",
    "Janis Joplin",
    "Jay-Z",
    "Jelly Roll Morton",
    "Jerry Lee Lewis",
    "Jethro Tull",
    "Jimi Hendrix",
    "Jimmie Rodgers",
    "Jimmy Dorsey",
    "Jimmy Reed",
    "Joan Baez",
    "John Coltrane",
    "John Denver",
    "John Fogerty & Creedence Clearwater Revival",
    "John Lee Hooker",
    "John Lennon",
    "Johnny Cash",
    "Johnny Mathis",
    "Joni Mitchell",
    "Judy Collins",
    "Judy Garland",
    "Justin Timberlake",
    "Kanye West",
    "Kendrick Lamar",
    "Kenny Rogers",
    "King Crimson",
    "Kingston Trio",
    "Kinks",
    "Kool and the Gang",
    "Kraftwerk",
    "LL Cool J",
    "Lady Gaga",
    "Leadbelly",
    "Led Zeppelin",
    "Lester Young",
    "Lil Wayne",
    "Linda Ronstadt",
    "Lionel Hampton",
    "Lionel Richie / Commodores",
    "Little Richard",
    "Little Walter",
    "Lonnie Johnson",
    "Loretta Lynn",
    "Louis Armstrong",
    "Louis Jordan",
    "Luther Vandross",
    "Lynyrd Skynyrd",
    "Ma Rainey",
    "Madonna",
    "Mahalia Jackson",
    "Mariah Carey",
    "Martha and the Vandellas",
    "Marty Robbins",
    "Marvin Gaye",
    "Mary J. Blige",
    "Merle Haggard",
    "Metallica",
    "Michael Jackson / Jackson 5",
    "Miles Davis",
    "Mills Brothers",
    "Moody Blues",
    "Muddy Waters",
    "N.W.A",
    "Nas",
    "Nat King Cole",
    "Neil Diamond",
    "Neil Young",
    "Nina Simone",
    "Nirvana",
    "O'Jays",
    "Ornette Coleman",
    "Otis Redding",
    "Outkast",
    "Ozzy Osbourne / Black Sabbath",
    "Patsy Cline",
    "Patti Page",
    "Paul McCartney and Wings",
    "Paul Simon & Art Garfunkel",
    "Paul Whiteman",
    "Pearl Jam",
    "Peggy Lee",
    "Perry Como",
    "Pete Seeger and the Weavers",
    "Peter, Paul and Mary",
    "Pink Floyd",
    "Platters",
    "Police / Sting",
    "Prince",
    "Professor Longhair",
    "Public Enemy",
    "Queen",
    "R. Kelly",
    "R.E.M.",
    "Radiohead",
    "Ramones",
    "Ravens",
    "Ray Charles",
    "Ray Price",
    "Reba McEntire",
    "Red Hot Chili Peppers",
    "Rev. James Cleveland",
    "Rick Nelson",
    "Rihanna",
    "Robert Johnson",
    "Robins / Coasters",
    "Rod Stewart",
    "Rolling Stones",
    "Roy Acuff",
    "Roy Orbison",
    "Run-D.M.C.",
    "Ruth Brown",
    "Sam Cooke",
    "Sammy Kaye",
    "Santana",
    "Sarah Vaughan",
    "Scott Joplin",
    "Shirelles",
    "Sister Rosetta Tharpe",
    "Sly and the Family Stone",
    "Smokey Robinson and the Miracles",
    "Son House",
    "Sonny Boy Williamson I (John Lee Williamson)",
    "Sonny Boy Williamson II (Rice Miller)",
    "Sonny Rollins",
    "Sonny Til and the Orioles",
    "Soul Stirrers",
    "Spinners",
    "Stan Getz",
    "Staple Singers",
    "Stevie Wonder",
    "T-Bone Walker",
    "Talking Heads / David Byrne",
    "Tammy Wynette",
    "Tampa Red",
    "Taylor Swift",
    "Ted Lewis",
    "Temptations",
    "Tennessee Ernie Ford",
    "The Band",
    "The Clash",
    "The Notorious B.I.G.",
    "The Who",
    "Thelonious Monk",
    "Tito Puente",
    "Tom Petty and the Heartbreakers",
    "Tommy Dorsey",
    "Tony Bennett",
    "U2",
    "Van Halen",
    "Van Morrison",
    "Velvet Underground",
    "Waylon Jennings",
    "Webb Pierce",
    "Whitney Houston",
    "Willie Nelson",
    "Wilson Pickett",
    "Woody Guthrie",
    "Wynonie Harris",
    "Yardbirds",
    "Yes"
};
}
