#include "MovieData.h"

namespace faker
{
const std::array<std::string_view, 299> actors = {
    "Aamir Khan",
    "Abbott and Costello",
    "Adel Imam",
    "Ahmed Zaki",
    "Al Pacino",
    "Alain Delon",
    "Alan Arkin",
    "Alan Rickman",
    "Alastair Sim",
    "Albert Finney",
    "Alberto Sordi",
    "Alec Guinness",
    "Amitabh Bachchan",
    "Andy Serkis",
    "Anthony Hopkins",
    "Anthony Perkins",
    "Anthony Quinn",
    "Armin Mueller-Stahl",
    "Arnold Schwarzenegger",
    "Arthur Kennedy",
    "Bela Lugosi",
    "Ben Kingsley",
    "Benicio del Toro",
    "Bill Murray",
    "Bing Crosby",
    "Bob Hope",
    "Bob Hoskins",
    "Boris Karloff",
    "Bourvil",
    "Brad Pitt",
    "Brendan Gleeson",
    "Bruce Lee",
    "Bruno Ganz",
    "Burt Lancaster",
    "Buster Keaton",
    "Cantinflas",
    "Cary Grant",
    "Charles Boyer",
    "Charles Chaplin",
    "Charles Laughton",
    "Charlton Heston",
    "Chishu Ryu",
    "Choi Min-sik",
    "Chow Yun-fat",
    "Chris Cooper",
    "Christian Bale",
    "Christopher Lee",
    "Christopher Walken",
    "Clark Gable",
    "Claude Rains",
    "Clint Eastwood",
    "Conrad Veidt",
    "Dana Andrews",
    "Daniel Auteuil",
    "Daniel Day-Lewis",
    "David Niven",
    "Denholm Elliott",
    "Dennis Hopper",
    "Denzel Washington",
    "Dev Anand",
    "Dilip Kumar",
    "Dirk Bogarde",
    "Don Cheadle",
    "Donald Crisp",
    "Donald Sutherland",
    "Douglas Fairbanks",
    "Dustin Hoffman",
    "Ed Harris",
    "Edward Everett Horton",
    "Edward G. Robinson",
    "Edward Norton",
    "Eli Wallach",
    "Emil Jannings",
    "Erich von Stroheim",
    "Erland Josephson",
    "Ernest Borgnine",
    "Errol Flynn",
    "Ewan McGregor",
    "Farid Shawqi",
    "Fernandel",
    "Fernando Fernán Gómez",
    "Fernando Rey",
    "Frank Sinatra",
    "Fred Astaire",
    "Fredric March",
    "Gael García Bernal",
    "Gary Cooper",
    "Gary Oldman",
    "Gaston Modot",
    "Gene Hackman",
    "Gene Kelly",
    "Gene Wilder",
    "Geoffrey Rush",
    "George C. Scott",
    "George Clooney",
    "George Sanders",
    "Gert Fröbe",
    "Gian Maria Volonté",
    "Giancarlo Giannini",
    "Glenn Ford",
    "Gregory Peck",
    "Groucho Marx / The Marx Brothers",
    "Gunnar Björnstrand",
    "Gérard Depardieu",
    "Gérard Philipe",
    "Harold Lloyd",
    "Harrison Ford",
    "Harry Dean Stanton",
    "Harvey Keitel",
    "Heath Ledger",
    "Henry Fonda",
    "Humphrey Bogart",
    "Ian McKellen",
    "Innokenty Smoktunovsky",
    "Jack Lemmon",
    "Jack Nicholson",
    "Jackie Chan",
    "Jacques Tati",
    "Jake Gyllenhaal",
    "James Caan",
    "James Cagney",
    "James Coburn",
    "James Dean",
    "James Earl Jones",
    "James Mason",
    "James Woods",
    "Jason Robards",
    "Javier Bardem",
    "Jean Gabin",
    "Jean Hersholt",
    "Jean Marais",
    "Jean-Claude Brialy",
    "Jean-Louis Trintignant",
    "Jean-Paul Belmondo",
    "Jean-Pierre Léaud",
    "Jeff Bridges",
    "Jeremy Irons",
    "Jerry Lewis",
    "Jim Carrey",
    "Joaquin Phoenix",
    "Joe Pesci",
    "Joel McCrea",
    "John Barrymore",
    "John Carradine",
    "John Cleese",
    "John Gielgud",
    "John Gilbert",
    "John Hurt",
    "John Malkovich",
    "John Travolta",
    "John Wayne",
    "Johnny Depp",
    "Jon Voight",
    "Joseph Cotten",
    "José Ferrer",
    "Karl Malden",
    "Kenneth Branagh",
    "Kevin Spacey",
    "King Baggot",
    "Kirk Douglas",
    "Klaus Kinski",
    "Laurel and Hardy",
    "Laurence Olivier",
    "Lee J. Cobb",
    "Lee Marvin",
    "Leonardo DiCaprio",
    "Leslie Cheung",
    "Leslie Howard",
    "Liam Neeson",
    "Lionel Barrymore",
    "Lon Chaney",
    "Louis de Funès",
    "Mack Sennett",
    "Marcello Mastroianni",
    "Marlon Brando",
    "Martin Balsam",
    "Martin Landau",
    "Martin Sheen",
    "Matt Damon",
    "Matthew McConaughey",
    "Max Linder",
    "Max von Sydow",
    "Maximilian Schell",
    "Mel Gibson",
    "Melvyn Douglas",
    "Michael Caine",
    "Michael Chekhov",
    "Michael Douglas",
    "Michael Fassbender",
    "Michael Redgrave",
    "Michel Piccoli",
    "Michel Serrault",
    "Michel Simon",
    "Mickey Rooney",
    "Montgomery Clift",
    "Morgan Freeman",
    "Nanni Moretti",
    "Naseeruddin Shah",
    "Nicolas Cage",
    "Nikolay Cherkasov",
    "Nino Manfredi",
    "Omar Sharif",
    "Orson Welles",
    "Paul Muni",
    "Paul Newman",
    "Paul Robeson",
    "Paul Scofield",
    "Paul Winfield",
    "Pedro Infante",
    "Peter Cushing",
    "Peter Finch",
    "Peter Lorre",
    "Peter O'Toole",
    "Peter Sellers",
    "Philip Seymour Hoffman",
    "Philippe Noiret",
    "Raimu",
    "Raj Kapoor",
    "Rajesh Khanna",
    "Ralph Fiennes",
    "Ralph Richardson",
    "Rex Harrison",
    "Richard Attenborough",
    "Richard Burton",
    "Richard Dreyfuss",
    "Richard Gere",
    "Richard Harris",
    "Richard Widmark",
    "Robert De NiroJames Stewart",
    "Robert Donat",
    "Robert Downey Jr.",
    "Robert Duvall",
    "Robert Mitchum",
    "Robert Redford",
    "Robert Ryan",
    "Robert Shaw",
    "Roberto Benigni",
    "Robin Williams",
    "Rock Hudson",
    "Rod Steiger",
    "Ronald Colman",
    "Roscoe 'Fatty' Arbuckle",
    "Roy Scheider",
    "Rudolf Klein-Rogge",
    "Rudolph Valentino",
    "Russell Crowe",
    "Rutger Hauer",
    "Ryan Gosling",
    "Samuel L. Jackson",
    "Sean Connery",
    "Sean Penn",
    "Sessue Hayakawa",
    "Shah Rukh Khan",
    "Sidney Poitier",
    "Spencer Tracy",
    "Stellan Skarsgård",
    "Sterling Hayden",
    "Steve Buscemi",
    "Steve Martin",
    "Steve McQueen",
    "Takashi Shimura",
    "Takeshi Kitano",
    "Tatsuya Nakadai",
    "The Three Stooges",
    "Thomas Mitchell",
    "Tim Robbins",
    "Tom Courtenay",
    "Tom Cruise",
    "Tom Hanks",
    "Tommy Lee Jones",
    "Tony Curtis",
    "Tony Leung Chiu Wai",
    "Toshiro Mifune",
    "Totò",
    "Ugo Tognazzi",
    "Uttam Kumar",
    "Victor Mature",
    "Victor McLaglen",
    "Viggo Mortensen",
    "Vincent Cassel",
    "Vincent Price",
    "Vittorio Gassman",
    "W.C. Fields",
    "Wallace Beery",
    "Walter Brennan",
    "Walter Huston",
    "Walter Matthau",
    "Walter Pidgeon",
    "Warren Beatty",
    "Will Smith",
    "Willem Dafoe",
    "William Holden",
    "William Hurt",
    "William Powell",
    "William S. Hart",
    "Woody Allen",
    "Woody Harrelson",
    "Yul Brynner",
    "Yves Montand"
};

const std::array<std::string_view, 300> actresses = {
    "Agnes Moorehead",
    "Aishwarya Rai",
    "Alida Valli",
    "Amy Adams",
    "Angela Bassett",
    "Angela Lansbury",
    "Angelina Jolie",
    "Anjelica Huston",
    "Ann-Margret",
    "Anna Karina",
    "Anna Magnani",
    "Anna May Wong",
    "Anne Bancroft",
    "Anne Baxter",
    "Anne Hathaway",
    "Anne Revere",
    "Annette Bening",
    "Annie Girardot",
    "Anouk Aimée",
    "Arletty",
    "Asha Parekh",
    "Asta Nielsen",
    "Audrey Hepburn",
    "Audrey Tautou",
    "Ava Gardner",
    "Barbara Hershey",
    "Barbara Stanwyck",
    "Barbra Streisand",
    "Bette Davis",
    "Bette Midler",
    "Betty Grable",
    "Beulah Bondi",
    "Bibi Andersson",
    "Blanche Sweet",
    "Brenda Blethyn",
    "Brigitte Bardot",
    "Cameron Diaz",
    "Carmen Maura",
    "Carmen Miranda",
    "Carole Lombard",
    "Cate Blanchett",
    "Catherine Deneuve",
    "Catherine Frot",
    "Catherine Zeta-Jones",
    "Charlize Theron",
    "Charlotte Gainsbourg",
    "Charlotte Rampling",
    "Claire Trevor",
    "Clara Bow",
    "Clara Kimball Young",
    "Claudette Colbert",
    "Claudia Cardinale",
    "Colleen Moore",
    "Danielle Darrieux",
    "Debbie Reynolds",
    "Deborah Kerr",
    "Debra Winger",
    "Delphine Seyrig",
    "Diane Keaton",
    "Diane Ladd",
    "Dianne Wiest",
    "Dolores Costello",
    "Dolores del Río",
    "Donna Reed",
    "Doris Day",
    "Dorothy Dandridge",
    "Dorothy Gish",
    "Edith Evans",
    "Eleanor Parker",
    "Elizabeth Taylor",
    "Ellen Burstyn",
    "Elsa Lanchester",
    "Emily Watson",
    "Emma Stone",
    "Emma Thompson",
    "Emmanuelle Béart",
    "Emmanuelle Riva",
    "Ethel Barrymore",
    "Eva Marie Saint",
    "Faina Ranevskaya",
    "Fanny Ardant",
    "Fatemeh Motamed-Arya",
    "Faten Hamama",
    "Faye Dunaway",
    "Florence Lawrence",
    "Frances McDormand",
    "Francesca Bertini",
    "Geena Davis",
    "Gena Rowlands",
    "Gene Tierney",
    "Geraldine Page",
    "Gina Lollobrigida",
    "Ginger Rogers",
    "Gisèle Casadesus",
    "Giulietta Masina",
    "Glenda Jackson",
    "Glenn Close",
    "Gloria Grahame",
    "Gloria Swanson",
    "Goldie Hawn",
    "Golshifteh Farahani",
    "Gong Li",
    "Grace Kelly",
    "Greer Garson",
    "Greta Garbo",
    "Gwyneth Paltrow",
    "Halle Berry",
    "Hamideh Kheiradabi",
    "Hanna Schygulla",
    "Harriet Andersson",
    "Hedy Lamarr",
    "Helen Mirren",
    "Helena Bonham Carter",
    "Hema Malini",
    "Henny Porten",
    "Hilary Swank",
    "Hind Rostom",
    "Holly Hunter",
    "Ingrid Bergman",
    "Ingrid Thulin",
    "Irene Dunne",
    "Irène Jacob",
    "Isabelle Adjani",
    "Isabelle Huppert",
    "Jacqueline Bisset",
    "Jane Alexander",
    "Jane Fonda",
    "Jane Wyman",
    "Janet Gaynor",
    "Janet Leigh",
    "Jaya Bachchan",
    "Jayne Mansfield",
    "Jean Arthur",
    "Jean Harlow",
    "Jean Seberg",
    "Jean Simmons",
    "Jeanne Moreau",
    "Jennifer Connelly",
    "Jennifer Jason Leigh",
    "Jennifer Jones",
    "Jennifer Lawrence",
    "Jessica Chastain",
    "Jessica Lange",
    "Jessica Tandy",
    "Joan Allen",
    "Joan Bennett",
    "Joan Blondell",
    "Joan Crawford",
    "Joan Fontaine",
    "Joanne Woodward",
    "Jodie Foster",
    "Judi Dench",
    "Judith Anderson",
    "Judy Davis",
    "Judy Garland",
    "Julia Roberts",
    "Julianne Moore",
    "Julie Andrews",
    "Julie Christie",
    "Juliette Binoche",
    "Kajol",
    "Kate Winslet",
    "Katharine Hepburn",
    "Kathleen Turner",
    "Kathy Bates",
    "Katy Jurado",
    "Keira Knightley",
    "Kinuyo Tanaka",
    "Kristin Scott Thomas",
    "Kyoko Kagawa",
    "Lana Turner",
    "Laura Dern",
    "Laura Linney",
    "Lauren Bacall",
    "Lee Remick",
    "Leila Hatami",
    "Leslie Caron",
    "Lilli Palmer",
    "Lillian Gish",
    "Liv Ullmann",
    "Liza Minnelli",
    "Louise Brooks",
    "Luise Rainer",
    "Lupe Vélez",
    "Lyubov Orlova",
    "Lyudmila Gurchenko",
    "Mabel Normand",
    "Machiko Kyo",
    "Madhubala",
    "Madhuri Dixit",
    "Mae West",
    "Maggie Cheung",
    "Maggie Smith",
    "Marcia Gay Harden",
    "Margherita Buy",
    "Maria Félix",
    "Maria Montez",
    "Maria Ouspenskaya",
    "Maria Schell",
    "Mariam Fakhr Eddine",
    "Mariangela Melato",
    "Maribel Verdú",
    "Marie Dressler",
    "Marilyn Monroe",
    "Marion Cotillard",
    "Marisa Tomei",
    "Marlene Dietrich",
    "Mary Astor",
    "Mary Pickford",
    "Mary Queeny",
    "María Antonieta Pons",
    "Maureen O'Hara",
    "Maureen Stapleton",
    "Meena Kumari",
    "Mercedes McCambridge",
    "Meryl Streep",
    "Mia Farrow",
    "Michelle Pfeiffer",
    "Michelle Williams",
    "Michelle Yeoh",
    "Michèle Morgan",
    "Mieko Harada",
    "Miou-Miou",
    "Miriam Hopkins",
    "Monica Bellucci",
    "Monica Vitti",
    "Myrna Loy",
    "Naomi Watts",
    "Nargis",
    "Natalie Portman",
    "Natalie Wood",
    "Nathalie Baye",
    "Nicole Kidman",
    "Nimmi",
    "Norma Shearer",
    "Norma Talmadge",
    "Nutan",
    "Octavia Spencer",
    "Olivia de Havilland",
    "Patricia Neal",
    "Paulette Goddard",
    "Penélope Cruz",
    "Piper Laurie",
    "Pola Negri",
    "Raquel Welch",
    "Reese Witherspoon",
    "Renée Zellweger",
    "Rita Hayworth",
    "Romy Schneider",
    "Rooney Mara",
    "Rosalind Russell",
    "Ruan Lingyu",
    "Ruth Gordon",
    "Sally Field",
    "Salma Hayek",
    "Sandra Bullock",
    "Sandrine Bonnaire",
    "Sara García",
    "Scarlett Johansson",
    "Setsuko Hara",
    "Shadia",
    "Sharon Stone",
    "Shelley Winters",
    "Shirley MacLaine",
    "Shirley Temple",
    "Shohreh Aghdashloo",
    "Sigourney Weaver",
    "Silvana Mangano",
    "Simone Signoret",
    "Simone Simon",
    "Sissy Spacek",
    "Soad Hosny",
    "Sophia Loren",
    "Sridevi",
    "Stefania Sandrelli",
    "Stéphane Audran",
    "Suchitra Sen",
    "Susan Hayward",
    "Susan Sarandon",
    "Sylvia Chang",
    "Teresa Wright",
    "Theda Bara",
    "Thelma Ritter",
    "Tilda Swinton",
    "Uma Thurman",
    "Valeria Golino",
    "Vanessa Redgrave",
    "Vera Kholodnaya",
    "Veronica Lake",
    "Victoria Abril",
    "Vilma Bánky",
    "Viola Davis",
    "Virna Lisi",
    "Vivien Leigh",
    "Vyjayanthimala",
    "Wendy Hiller",
    "Whoopi Goldberg",
    "Winona Ryder",
    "Yousra",
    "Zhang Ziyi"
};

}