name: bazel

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'LICENSE'
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'LICENSE'

jobs:
  bazel:
    name: ci-ubuntu-24.04-gcc-bazel
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Cache Bazel
        id: cache-bazel
        uses: actions/cache@v4.0.2
        env:
          cache-name: cache-bazel-data
        with:
          path: /home/runner/.cache/bazel/_bazel_runner
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build faker-cxx library
        run: bazel build //:faker-cxx

      - name: Build faker-cxx examples and run
        run: |
          bazel build //examples:faker-cxx-basic-example
          bazel build //examples:faker-cxx-person-example
          bazel-bin/examples/faker-cxx-person-example
          bazel-bin/examples/faker-cxx-basic-example

      - name: Build faker-cxx tests and validate
        run: |
          bazel build //tests:faker-cxx-ut
          bazel-bin/tests/faker-cxx-ut
