name: mingw

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        id: setup
        with:
          platform: x64

      - run: cmake -E make_directory build

      - working-directory: build/
        run: cmake .. -GNinja -DCMAKE_CXX_COMPILER='${{ steps.setup.outputs.gxx }}' -DCMAKE_C_COMPILER='${{ steps.setup.outputs.gcc }}' 

      - working-directory: build/
        run: cmake --build .

      - working-directory: build/
        run: ctest -C Debug --output-on-failure